version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - goconst
    - bodyclose
    - noctx
    - exhaustive
    - nakedret
    - prealloc
    - revive

  settings:
    govet:
      enable-all: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: unreachable-code
        - name: var-naming
    nakedret:
      max-func-lines: 30

issues:
  exclude-dirs:
    - experiments
    - hack

output:
  formats:
    text:
      color-mode: colored

  sort-results: true
  sort-order:
    - linter
    - severity
    - file
