package repos

import (
	"bytes"
	"context"
	"fmt"
	"slices"
	"strings"

	"github.com/fullsend-ai/fullsend/internal/forge"
	"gopkg.in/yaml.v3"
)

// fullsendPipelineInclude is the include entry that points to the
// fullsend-owned pipeline wrapper file.
const fullsendPipelineInclude = ".gitlab/ci/fullsend-pipeline.yml"

// fullsendDispatchInclude is the local include entry fullsend versions
// before #7322 used to pull in the native merge_request_event dispatch
// job. It's no longer referenced by the current fullsend-pipeline.yml
// template, but an already-enrolled repo whose on-repo wrapper predates
// #7322 may still include it — see
// gitlabPipelineWrapperStillIncludesDispatch.
const fullsendDispatchInclude = ".gitlab/ci/fullsend-dispatch.yml"

// fullsendWorkflowNamePrefix is the prefix of the workflow.name value
// generated by newGitLabCI. Used during unmerge to remove the
// fullsend-specific workflow name.
const fullsendWorkflowNamePrefix = "fullsend "

// fullsendStages are the pipeline stages that fullsend's jobs currently
// use. GitLab's deep merge only applies to hash maps — stages: is a YAML
// array and is overwritten, not merged (see gitlab-org/gitlab#29980).
// When the root .gitlab-ci.yml already defines stages:, the included
// file's stages are silently dropped, so these must be added directly
// to the root file.
//
// Native merge_request_event dispatch was removed in #7322, leaving
// "dispatch" as an empty stage. #7337 dropped it from this required
// set so new installs and drift detection no longer emit or require
// it. Uninstall and converge still strip it via obsoleteGitLabStages.
var fullsendStages = []string{"poll", "agent"}

// obsoleteGitLabStages are stages that previous fullsend versions
// installed into stages: but that are no longer part of the current
// contract. StripObsoleteGitLabStages uses this list to migrate
// already-enrolled repos in place; removeStages uses it so uninstall
// still cleans the leftover up on repos that predate #7337.
var obsoleteGitLabStages = []string{"dispatch"}

// nonJobTopLevelKeys are .gitlab-ci.yml top-level keys reserved for
// pipeline configuration rather than job definitions. stageReferencedByJob
// uses this list (together with the `.`-prefixed hidden-key convention)
// to tell job definitions — which may carry a stage: value — apart from
// configuration blocks that happen to be top-level mappings too.
//
// "pages" is deliberately absent: unlike the other keys here, it isn't a
// global pipeline keyword — it's GitLab's reserved name for the Pages
// deploy job, which can carry its own stage: value like any other job.
// Treating it as configuration would let a `pages: {stage: dispatch}`
// job's stage get stripped out from under it.
var nonJobTopLevelKeys = map[string]bool{
	"stages":        true,
	"workflow":      true,
	"include":       true,
	"variables":     true,
	"default":       true,
	"image":         true,
	"services":      true,
	"before_script": true,
	"after_script":  true,
	"cache":         true,
}

// fullsendWorkflowRules are the workflow:rules entries that fullsend
// requires in the root .gitlab-ci.yml. GitLab does not merge workflow:
// definitions across includes, so these must be in the root file.
// Native merge_request_event dispatch was removed in #7322; all events
// route through the cron poller (schedule) and API-triggered agent jobs.
var fullsendWorkflowRules = []workflowRule{
	{If: `$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true"`},
	{If: `$CI_PIPELINE_SOURCE == "api" && $CI_COMMIT_REF_PROTECTED == "true" && $STAGE`},
}

// unmergeWorkflowRules are the current fullsend rules removed on uninstall
// unconditionally. This deliberately excludes the obsolete
// native-MR-dispatch rule ($CI_PIPELINE_SOURCE == "merge_request_event")
// that fullsend versions before #7322 installed: it's GitLab's standard,
// widely-used MR-pipeline gate, not something unique to fullsend, and
// MergeGitLabCI no longer installs it for any repo going forward. The
// obsolete rule is only removed on uninstall when the workflow block
// carries fullsend's provenance marker (see removeWorkflowRules); absent
// that marker, unconditionally removing it would risk deleting a repo's
// own independently-configured MR gate, so it is left in place — an
// acceptable, one-shot leftover since uninstall is a single user action.
var unmergeWorkflowRules = []workflowRule{
	{If: `$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true"`},
	{If: `$CI_PIPELINE_SOURCE == "api" && $CI_COMMIT_REF_PROTECTED == "true" && $STAGE`},
}

// workflowRule represents a single GitLab CI workflow:rules entry
// identified by its if: condition.
type workflowRule struct {
	If string
}

// obsoleteGitLabWorkflowRules are workflow:rules entries that previous
// fullsend versions installed into the root .gitlab-ci.yml but that are
// no longer part of the current contract. Native merge_request_event
// dispatch was removed in #7322; on an already-enrolled repo, this rule
// otherwise survives `repos upgrade`/`repos install` convergence forever
// because the install merge path only runs on fresh installs and the
// uninstall unmerge path only runs on teardown. StripObsoleteGitLabWorkflowRules
// uses this list to migrate already-enrolled repos in place.
var obsoleteGitLabWorkflowRules = []workflowRule{
	{If: `$CI_PIPELINE_SOURCE == "merge_request_event"`},
}

// StripObsoleteGitLabWorkflowRules removes obsolete fullsend workflow:rules
// entries (see obsoleteGitLabWorkflowRules) from an existing .gitlab-ci.yml,
// leaving everything else — including fullsend's current rules, the
// workflow name, auto_cancel settings, and any user configuration —
// untouched. Unlike UnmergeGitLabCI (full teardown) this never removes
// fullsend's current entries; it only migrates away rules that are
// strictly obsolete.
//
// An obsolete rule is only stripped when gitlabCIWorkflowIsFullsendOwned
// finds positive evidence that fullsend, not the repo owner, installed
// the workflow block — the obsolete condition
// ($CI_PIPELINE_SOURCE == "merge_request_event") is GitLab's standard
// MR-pipeline gate and repos commonly set it themselves.
//
// Returns the original content and changed=false when there is nothing
// to strip (no workflow: block, no rules:, no obsolete rule present, or
// fullsend ownership of the block can't be established).
func StripObsoleteGitLabWorkflowRules(existing []byte) (result []byte, changed bool, err error) {
	if len(bytes.TrimSpace(existing)) == 0 {
		return existing, false, nil
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return nil, false, fmt.Errorf("parsing .gitlab-ci.yml: %w", err)
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return existing, false, nil
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return existing, false, nil
	}

	workflowVal := findMappingValue(root, "workflow")
	if workflowVal == nil || workflowVal.Kind != yaml.MappingNode {
		return existing, false, nil
	}

	rulesIdx := findMappingKeyIndex(workflowVal, "rules")
	if rulesIdx < 0 {
		return existing, false, nil
	}
	rulesVal := workflowVal.Content[rulesIdx+1]
	if rulesVal.Kind != yaml.SequenceNode {
		return existing, false, nil
	}

	obsolete := make(map[string]bool, len(obsoleteGitLabWorkflowRules))
	for _, r := range obsoleteGitLabWorkflowRules {
		obsolete[r.If] = true
	}

	hasObsolete := false
	for _, item := range rulesVal.Content {
		if item.Kind == yaml.MappingNode {
			if v := findMappingValue(item, "if"); v != nil && obsolete[v.Value] {
				hasObsolete = true
				break
			}
		}
	}
	if !hasObsolete {
		return existing, false, nil
	}

	// $CI_PIPELINE_SOURCE == "merge_request_event" is GitLab's standard
	// MR-pipeline gate, not something unique to fullsend, and repos can
	// (and do) set it themselves. Only strip it when there is positive
	// evidence fullsend — not the repo owner — installed this workflow
	// block; otherwise leave it untouched.
	if !gitlabCIWorkflowIsFullsendOwned(workflowVal) {
		return existing, false, nil
	}

	var kept []*yaml.Node
	for _, item := range rulesVal.Content {
		if item.Kind == yaml.MappingNode {
			if v := findMappingValue(item, "if"); v != nil && obsolete[v.Value] {
				continue
			}
		}
		kept = append(kept, item)
	}
	if len(kept) == 0 {
		// Remove the rules: key entirely rather than leaving behind
		// workflow.rules: []. GitLab treats a present-but-empty rules:
		// as "never run" (see https://docs.gitlab.com/ee/ci/yaml/#workflow),
		// which would also block fullsend's own schedule- and
		// API-triggered pipelines, not just MR pipelines. Mirrors
		// removeWorkflowRules's teardown-path handling of the same case.
		workflowVal.Content = append(
			workflowVal.Content[:rulesIdx],
			workflowVal.Content[rulesIdx+2:]...)
	} else {
		rulesVal.Content = kept
	}

	out, marshalErr := marshalNode(&doc)
	if marshalErr != nil {
		return nil, false, marshalErr
	}
	return out, true, nil
}

// gitlabCIWorkflowIsFullsendOwned reports whether a workflow: block shows
// positive evidence that fullsend, rather than the repo owner, installed
// it: the workflow carries the fullsend-generated name (set by
// newGitLabCI on fresh installs).
//
// Co-presence of fullsend's current schedule/api rules is deliberately
// NOT treated as a signal. mergeWorkflowRules appends fullsend's rules
// into ANY pre-existing workflow block unconditionally, regardless of
// what other rules that block already has, and never sets workflow.name
// (see newGitLabCI's doc comment). So a repo that independently
// configured its own merge_request_event gate and then enrolled fullsend
// via the merge path ends up with a rules set that "matches" fullsend's
// current required rules purely by coincidence of the merge having run —
// that only proves fullsend added *some* rules to this block, not that
// it added any particular other rule found alongside them. Absent the
// name signal, the block cannot be distinguished from one the repo owner
// configured independently.
func gitlabCIWorkflowIsFullsendOwned(workflow *yaml.Node) bool {
	nameVal := findMappingValue(workflow, "name")
	return nameVal != nil && strings.HasPrefix(nameVal.Value, fullsendWorkflowNamePrefix)
}

// StripObsoleteGitLabStages removes obsolete fullsend stages (see
// obsoleteGitLabStages) from an existing .gitlab-ci.yml, leaving
// everything else — including fullsend's current stages, user stages,
// includes, and workflow configuration — untouched. Unlike UnmergeGitLabCI
// (full teardown) this never removes fullsend's current stages; it only
// migrates away stages that are strictly obsolete.
//
// An obsolete stage is only a stripping candidate when the file shows
// positive evidence that fullsend, not the repo owner, installed it: the
// fullsend pipeline include is present (this is an enrolled root CI
// file) AND at least one current fullsend stage is in the stages list
// (mergeStages ran and appended poll/agent alongside dispatch).
// A lone "dispatch" stage without poll or agent is treated as the
// repo's own and left in place. This gate differs from
// gitlabCIWorkflowIsFullsendOwned (workflow.name) because mergeStages
// never sets workflow.name — the merge-path repos that actually have
// stages: in the root file are exactly those that lack the name
// marker. Gating on the name would make this migration a no-op for
// the files that need it. "dispatch" is also not GitLab's standard
// MR-pipeline gate; the include-plus-current-stage fingerprint is
// the analogue of fullsend ownership for stages.
//
// That fingerprint proves fullsend touched the stages: array, but not
// that a stage literally named "dispatch" is safe to delete — a repo
// enrolled via the merge path could independently have its own job on
// a "dispatch" stage, coexisting with fullsend's poll/agent. Deleting a
// stage that a job still references breaks the pipeline (GitLab rejects
// a job whose stage: isn't in stages:). So before removing an obsolete
// stage name, stageReferencedByJob scans top-level job definitions —
// including stages inherited via extends: or the YAML merge key (<<:) —
// for an effective stage: value matching it and, if found, leaves that
// stage in place — mirroring the conservative refusal
// gitlabCIWorkflowIsFullsendOwned already applies to the workflow: block.
// This scan only sees the root file's own top-level keys, so a second,
// non-fullsend include is also treated as absence of evidence: the root
// file might not be the whole picture, and a job living in that other
// include would be invisible to the scan.
//
// Returns the original content and changed=false when there is nothing
// to strip (no stages: block, no obsolete stage present, fullsend
// ownership of the stages list can't be established, a non-fullsend
// include is also present, or every obsolete stage present is still
// referenced by a job).
func StripObsoleteGitLabStages(existing []byte) (result []byte, changed bool, err error) {
	if len(bytes.TrimSpace(existing)) == 0 {
		return existing, false, nil
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return nil, false, fmt.Errorf("parsing .gitlab-ci.yml: %w", err)
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return existing, false, nil
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return existing, false, nil
	}

	// Top-level keys are resolved once via classifyTopLevelKey — the same
	// alias-resolving, tag-checking classifier stageReferencedByJob uses
	// for job keys — rather than the literal, first-match .Value=="include"
	// (or "stages") checks findMappingValue/findMappingKeyIndex perform. A
	// second top-level "include:" key hidden behind an AliasNode, or a
	// duplicate "include:"/"stages:" key that a first-match lookup would
	// silently collapse to its first occurrence, must be visible here: the
	// include-ownership gate below can only fail closed on what it can see.
	topKeys, topOk := classifyTopLevelKeys(root)
	if !topOk {
		return existing, false, nil
	}

	includeVals := topKeys["include"]
	if len(includeVals) == 0 {
		return existing, false, nil
	}
	if len(includeVals) > 1 {
		// Duplicate top-level "include:" keys — GitLab/Psych is last-wins,
		// but which occurrence actually wins can't be assumed with
		// confidence here, and a first-match lookup would make the other
		// occurrence (and any job it pulls in) invisible. Fail closed.
		return existing, false, nil
	}
	includeVal := includeVals[0]

	hasInclude := false
	hasOtherInclude := false
	if includeVal.Kind == yaml.SequenceNode {
		for _, item := range includeVal.Content {
			if isFullsendPipelineInclude(item) {
				hasInclude = true
			} else {
				hasOtherInclude = true
			}
		}
	} else {
		hasInclude = isFullsendPipelineInclude(includeVal)
	}
	if !hasInclude {
		return existing, false, nil
	}
	// A second include can pull in a local file that defines its own jobs.
	// stageReferencedByJob only sees the root file's top-level keys, so a
	// job living in that other include is invisible to it — stripping a
	// stage that job references would break the pipeline. Fail closed
	// rather than fetch and scan an arbitrary include graph.
	if hasOtherInclude {
		return existing, false, nil
	}

	stagesVals := topKeys["stages"]
	if len(stagesVals) == 0 {
		return existing, false, nil
	}
	if len(stagesVals) > 1 {
		// Duplicate top-level "stages:" keys — same last-wins ambiguity as
		// duplicate "include:" keys above. Fail closed.
		return existing, false, nil
	}
	stagesVal := stagesVals[0]
	if stagesVal.Kind != yaml.SequenceNode {
		return existing, false, nil
	}

	obsolete := make(map[string]bool, len(obsoleteGitLabStages))
	for _, s := range obsoleteGitLabStages {
		obsolete[s] = true
	}

	existingStages := make(map[string]bool)
	for _, item := range stagesVal.Content {
		if item.Kind == yaml.ScalarNode {
			existingStages[item.Value] = true
		}
	}

	hasObsolete := false
	for name := range obsolete {
		if existingStages[name] {
			hasObsolete = true
			break
		}
	}
	if !hasObsolete {
		return existing, false, nil
	}

	// A stages list that contains dispatch but none of fullsend's
	// current stages is indistinguishable from a repo that independently
	// named a stage "dispatch" and later added the fullsend include
	// without mergeStages having appended poll/agent. Leave it.
	hasCurrent := false
	for _, s := range fullsendStages {
		if existingStages[s] {
			hasCurrent = true
			break
		}
	}
	if !hasCurrent {
		return existing, false, nil
	}

	// Only remove an obsolete stage that's actually present and that no
	// job still references. A referenced stage is left in place even
	// though it's nominally obsolete — removing it would make the job's
	// stage: value invalid and break the pipeline.
	removable := make(map[string]bool, len(obsolete))
	for name := range obsolete {
		if existingStages[name] && !stageReferencedByJob(root, name) {
			removable[name] = true
		}
	}
	if len(removable) == 0 {
		return existing, false, nil
	}

	var kept []*yaml.Node
	for _, item := range stagesVal.Content {
		if item.Kind == yaml.ScalarNode && removable[item.Value] {
			continue
		}
		kept = append(kept, item)
	}
	// kept cannot be empty: hasCurrent already proved at least one
	// current fullsend stage is present, and those names are disjoint
	// from obsoleteGitLabStages.
	stagesVal.Content = kept

	out, marshalErr := marshalNode(&doc)
	if marshalErr != nil {
		return nil, false, marshalErr
	}
	return out, true, nil
}

// stageReferencedByJob reports whether any top-level job definition in
// root has an effective stage: of stageName — set directly, inherited via
// extends:, or inherited via the YAML merge key (<<:). Top-level keys
// reserved for pipeline configuration (see nonJobTopLevelKeys) are not
// job definitions and are skipped as scan roots, but hidden `.`-prefixed
// keys (templates meant to be extended, not run directly) are still
// resolved as extends/merge targets: a visible job with no stage: of its
// own can still compile to stageName by extending or merging in a hidden
// template that sets it. A job that still references an otherwise-obsolete
// stage name must keep that stage in stages: or GitLab rejects the
// pipeline, so callers use this to avoid stripping a stage a job depends
// on.
//
// A top-level key must be a resolvable, untagged scalar to be classified
// as reserved configuration, a hidden template, or an ordinary job name.
// A key that is instead an AliasNode (`*n: {stage: dispatch}`), carries a
// non-core YAML tag, or resolves to anything other than a plain scalar
// can't be classified — it might be a live job the classifier would
// otherwise skip. The root-level YAML merge key (<<:) is handled the same
// way: gopkg.in/yaml.v3's Node API preserves "<<" as a literal mapping
// key rather than expanding it, so a merged-in job (e.g. `<<: *jobs` where
// *jobs anchors `{notify: {stage: dispatch, ...}}`) is invisible to the
// per-key scan — the merge target would be checked as if it were a single
// job body, which has no top-level stage: of its own, rather than scanned
// per injected job. Both cases fail closed by returning true rather than
// being skipped via continue.
//
// classifyTopLevelKey (shared with collectJobKeys) is used for both the
// extends-target lookup table and the scan loop below, so the two can't
// drift apart on what counts as a classifiable key — a hidden template
// keyed by an AliasNode (`*n: &tpl .dispatch_template`) must be resolvable
// as an extends/merge target by the same rule that lets the scan loop
// recognize and skip it as a template, or a visible job extending it would
// miss the lookup entry and silently fail open.
func stageReferencedByJob(root *yaml.Node, stageName string) bool {
	lookup := make(map[string]*yaml.Node, len(root.Content)/2)
	for i := 0; i+1 < len(root.Content); i += 2 {
		if name, ok := classifyTopLevelKey(root.Content[i]); ok {
			lookup[name] = root.Content[i+1]
		}
	}

	for i := 0; i+1 < len(root.Content); i += 2 {
		keyNode := root.Content[i]
		valNode := root.Content[i+1]

		name, ok := classifyTopLevelKey(keyNode)
		if !ok {
			return true
		}
		if hasInterpolationSyntax(name) {
			// A top-level key whose literal text carries interpolation
			// syntax can't be trusted to classify as "<<", a hidden
			// template, or an ordinary job name: the interpolated portion
			// may evaluate to something else entirely at pipeline time. In
			// particular, an ordinary-looking name (not "<<", not
			// "."-prefixed) whose value is an alias to a mapping of further
			// job definitions — e.g. `$[[ inputs.merge ]]: *jobs` injecting
			// {notify: {stage: dispatch}} — would otherwise be scanned by
			// nodeResolvesToStage as a single job body, which has no
			// top-level stage: of its own, silently missing the injected
			// jobs. Fail closed before classifying this key at all, rather
			// than only guarding the "."-prefixed hidden-template case.
			return true
		}
		if name == "<<" {
			return true
		}
		if nonJobTopLevelKeys[name] {
			continue
		}
		if strings.HasPrefix(name, ".") {
			continue
		}
		if nodeResolvesToStage(valNode, stageName, lookup, make(map[*yaml.Node]bool)) {
			return true
		}
	}
	return false
}

// hasInterpolationSyntax reports whether a key or value's literal text
// carries GitLab pipeline-input interpolation syntax (`$[[ ... ]]`) or
// CI/CD variable-expansion syntax (`${...}`). A name containing either
// can't be trusted as a stable literal: it may evaluate to a different
// name entirely at pipeline time (e.g. a top-level key that resolves to
// "include" or "stages", or an ordinary-looking key that resolves to
// "stage"/"<<"/"extends"), so callers that need a proven identity — as
// opposed to classifyTopLevelKey's plain job-name classification, which
// intentionally keeps a literal, non-interpolated "$" in a job name
// scannable (e.g. "weird$job") — must fail closed on it instead of
// trusting the raw text.
func hasInterpolationSyntax(name string) bool {
	return strings.Contains(name, "$[[") || strings.Contains(name, "${")
}

// classifyTopLevelKey resolves a mapping key to a plain name usable for
// lookup and classification: an AliasNode is dereferenced first, and the
// result must be a plain, untagged ScalarNode. ok is false for anything
// else (an unresolvable/cyclic alias, a non-core-tagged key, or a
// non-scalar key) — such a key can't be classified as reserved
// configuration, a hidden template, or an ordinary job name, so callers
// must treat it conservatively (fail closed) rather than guess.
//
// This is the single source of truth for key classification shared by
// stageReferencedByJob's lookup-building and scanning loops and by
// collectJobKeys; each previously reimplemented this check slightly
// differently, which is how a hidden template keyed by an AliasNode could
// be recognized by one loop (and skipped as a template) while being
// invisible to the other (never added to the extends-target lookup).
func classifyTopLevelKey(keyNode *yaml.Node) (name string, ok bool) {
	resolved := keyNode
	if keyNode.Kind == yaml.AliasNode {
		resolved = resolveAlias(keyNode)
	}
	if resolved == nil || resolved.Kind != yaml.ScalarNode || hasNonCoreTag(resolved) {
		return "", false
	}
	return resolved.Value, true
}

// classifyTopLevelKeys walks every key/value pair in root once, resolving
// each key via classifyTopLevelKey, and collects every occurrence of each
// resolved name. ok is false — fail closed — when any top-level key can't
// be classified (an alias to something other than a plain untagged
// scalar, a non-core-tagged key, or a non-scalar key), since such a key
// might resolve to a name a caller needs to see (e.g. "include" or
// "stages") and would otherwise be silently invisible to it.
//
// This replaces separate, drifting top-level lookups — a literal
// .Value=="include" check for the include-ownership gate, a literal
// .Value=="stages" check for the stages list — with the same
// alias-resolving, tag-checking, duplicate-aware classification already
// required for job keys, so a second top-level "include:" key hidden
// behind an AliasNode, or a duplicate "include:"/"stages:" key that
// GitLab/Psych's last-wins semantics would apply, can't be silently
// collapsed to a single first-match occurrence the way findMappingValue
// and findMappingKeyIndex would collapse it.
//
// A key whose literal text carries interpolation syntax (`$[[ ... ]]` or
// `${...}`, see hasInterpolationSyntax) is also treated as unclassifiable
// here, even though classifyTopLevelKey itself resolved it to a plain
// scalar: e.g. a second top-level `$[[ inputs.extra ]]:` key could
// evaluate to "include" or "stages" at pipeline time, hiding a duplicate
// occurrence from the two lookups above. This check is scoped to
// classifyTopLevelKeys rather than classifyTopLevelKey itself so an
// ordinary, non-interpolated `$`-bearing job name (e.g. "weird$job")
// remains scannable via the shared helper's other callers.
func classifyTopLevelKeys(root *yaml.Node) (keys map[string][]*yaml.Node, ok bool) {
	keys = make(map[string][]*yaml.Node, len(root.Content)/2)
	ok = true
	for i := 0; i+1 < len(root.Content); i += 2 {
		name, keyOk := classifyTopLevelKey(root.Content[i])
		if !keyOk || hasInterpolationSyntax(name) {
			ok = false
			continue
		}
		keys[name] = append(keys[name], root.Content[i+1])
	}
	return keys, ok
}

// nodeResolvesToStage reports whether node's effective stage: — resolving
// alias nodes (e.g. `job: *template`), the YAML merge key (<<: *template
// or <<: [*a, *b]), and extends: chains (scalar or sequence, possibly
// pointing at another job that itself extends further) — equals
// stageName. A node's own explicit stage: always takes precedence over
// anything inherited, matching GitLab's merge semantics where a job's own
// keys override what it extends or merges in. seen guards against cyclic
// references.
//
// A stage: value that isn't a known literal — an AliasNode (`stage:
// *anchor`), an unresolvable/unexpected form such as GitLab's `!reference
// [...]` tag, or a plain scalar carrying GitLab CI/CD variable or
// pipeline-input interpolation syntax (`stage: $NOTIFY_STAGE`, `${...}`,
// `$[[ ... ]]`) whose `.Value` is unevaluated expression text rather than
// the stage GitLab will actually assign — cannot be compared as a string.
// isLiteralScalarValue applies this fail-closed check uniformly; anything
// it can't resolve to a literal is treated as a live reference since the
// effective stage can't be ruled out.
//
// The same fail-closed treatment applies to the whole-job value itself:
// after alias resolution, a node that carries a non-core YAML tag (such as
// a whole-job `!reference [...]`) or isn't a mapping can't be interpreted
// as job content, so it's treated as a live reference rather than silently
// skipped.
//
// stage:, <<:, and extends: are looked up via collectJobKeys rather than
// findMappingValue, which only returns the first match: gopkg.in/yaml.v3
// preserves duplicate mapping keys as separate Content pairs (the
// duplicate-key error only applies when decoding into a Go map/struct),
// and GitLab/Psych's YAML parser is last-wins, so a first-match lookup can
// silently classify a job by the wrong occurrence. collectJobKeys collects
// every occurrence of each key and reports ok=false — fail closed — when a
// key is duplicated or when any key in the mapping can't be classified as
// a unique, plain, untagged scalar (an alias key, a non-core-tagged key,
// or a non-scalar key), since such a key might itself resolve to "stage",
// "<<", or "extends" and be missed.
func nodeResolvesToStage(node *yaml.Node, stageName string, lookup map[string]*yaml.Node, seen map[*yaml.Node]bool) bool {
	if node == nil || seen[node] {
		return false
	}
	seen[node] = true

	if node.Kind == yaml.AliasNode {
		return nodeResolvesToStage(node.Alias, stageName, lookup, seen)
	}
	if hasNonCoreTag(node) || node.Kind != yaml.MappingNode {
		// A whole-job value that isn't a plain mapping after alias
		// resolution — e.g. GitLab's `notify: !reference
		// [.dispatch_template]` (a SequenceNode tagged !reference, not a
		// job mapping) — can't be interpreted as a job body, so its
		// effective stage can't be ruled out. Fail closed rather than
		// silently treat it as not referencing anything, matching the
		// same hasNonCoreTag guard already applied to stage:/<<:/extends:
		// values below.
		return true
	}

	keys, ok := collectJobKeys(node)
	if !ok {
		return true
	}

	if len(keys.stage) == 1 {
		value, ok := isLiteralScalarValue(keys.stage[0])
		if !ok {
			// Not a resolvable, untagged, fully-literal scalar — either an
			// unresolvable alias, a non-core tag such as `!reference`, a
			// non-scalar, or GitLab CI/CD variable/pipeline-input
			// interpolation (e.g. `stage: $NOTIFY_STAGE`). The effective
			// stage value isn't known here, so it can't be ruled out.
			return true
		}
		return value == stageName
	}

	if len(keys.merge) == 1 && mergeTargetResolvesToStage(keys.merge[0], stageName, lookup, seen) {
		return true
	}

	if len(keys.extends) == 1 {
		names, resolvable := extendsNames(keys.extends[0])
		if !resolvable {
			// extends: isn't a scalar, a sequence of scalars, or a
			// resolvable alias to one of those — e.g. an alias to a
			// mapping, or some other unexpected shape. The effective
			// extends target(s) can't be determined, so fail closed
			// rather than silently treat this job as not extending
			// anything.
			return true
		}
		for _, name := range names {
			target, found := lookup[name]
			if !found {
				// The extends: target isn't a top-level key of this root
				// file. GitLab resolves extends: against the fully merged
				// pipeline configuration, including jobs defined in
				// included files — an unresolvable name here doesn't mean
				// the job doesn't inherit stageName, only that this
				// scanner (which only sees the root file's own top-level
				// keys) can't rule it out. Fail closed rather than
				// silently treat the extends: target as absent.
				return true
			}
			if nodeResolvesToStage(target, stageName, lookup, seen) {
				return true
			}
		}
	}

	return false
}

// jobKeys holds every occurrence of the stage:, <<:, and extends: keys
// found on a job mapping by collectJobKeys.
type jobKeys struct {
	stage   []*yaml.Node
	merge   []*yaml.Node
	extends []*yaml.Node
}

// collectJobKeys walks every key/value pair in a job mapping and collects
// every occurrence of the stage:, <<:, and extends: keys — not just the
// first. ok is false (fail closed) when the mapping can't be
// unambiguously classified by key name: any key that isn't a unique,
// plain, untagged scalar (an AliasNode key, a key carrying a non-core YAML
// tag, or a non-scalar key), or more than one occurrence of stage:, <<:,
// or extends:. Both cases mean the mapping's effective stage:/<<:/extends:
// can't be determined from a simple by-name lookup, so callers must treat
// the job as a live reference rather than guess which occurrence wins.
//
// Key classification is delegated to classifyTopLevelKey, the same helper
// stageReferencedByJob uses, so job-level and top-level key resolution
// can't drift apart on what counts as a classifiable key.
func collectJobKeys(mapping *yaml.Node) (keys jobKeys, ok bool) {
	ok = true
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		valNode := mapping.Content[i+1]

		name, keyOk := classifyTopLevelKey(mapping.Content[i])
		if !keyOk {
			ok = false
			continue
		}
		if strings.Contains(name, "$") {
			// A job-level key whose literal text carries GitLab
			// pipeline-input interpolation syntax (e.g.
			// `$[[ inputs.keyword ]]: dispatch`) might evaluate to "stage",
			// "<<", or "extends" at pipeline time even though its raw
			// .Value never string-matches any of those names here. Treat
			// the whole mapping as unclassifiable rather than silently
			// ignore a key that could be one of the ones this scan depends
			// on.
			ok = false
			continue
		}

		switch name {
		case "stage":
			keys.stage = append(keys.stage, valNode)
		case "<<":
			keys.merge = append(keys.merge, valNode)
		case "extends":
			keys.extends = append(keys.extends, valNode)
		}
	}
	if len(keys.stage) > 1 || len(keys.merge) > 1 || len(keys.extends) > 1 {
		ok = false
	}
	return keys, ok
}

// mergeTargetResolvesToStage reports whether a YAML merge key's value (the
// `<<:` value, e.g. `<<: *template`, `<<: [*a, *b]`, or `<<: !reference
// [...]`) has an effective stage: of stageName once merged into the job
// that references it.
//
// The value must be alias-resolved before its Kind is inspected: an alias
// to a sequence of mappings (`<<: *seq`) is itself an AliasNode, not a
// SequenceNode, so classifying by Kind before dereferencing misses it and
// falls through to comparing the sequence as if it had no stage: of its
// own. A resolved sequence's items must each be alias-resolved and
// confirmed to be mappings in turn — GitLab's `<<: !reference [...]` form
// produces a sequence of path-component scalars, not job mappings, and
// must not be scanned as one. Any node that carries a non-core YAML tag
// (such as `!reference`) or that isn't a mapping/sequence after resolution
// can't be interpreted as merged job content, so its effective stage can't
// be ruled out — fail closed by returning true.
func mergeTargetResolvesToStage(mergeVal *yaml.Node, stageName string, lookup map[string]*yaml.Node, seen map[*yaml.Node]bool) bool {
	resolved := resolveAlias(mergeVal)
	if resolved == nil {
		// Cyclic alias chain — can't resolve.
		return true
	}
	if hasNonCoreTag(resolved) {
		return true
	}
	switch resolved.Kind {
	case yaml.MappingNode:
		return nodeResolvesToStage(resolved, stageName, lookup, seen)
	case yaml.SequenceNode:
		for _, item := range resolved.Content {
			itemResolved := resolveAlias(item)
			if itemResolved == nil || hasNonCoreTag(itemResolved) || itemResolved.Kind != yaml.MappingNode {
				return true
			}
			if nodeResolvesToStage(itemResolved, stageName, lookup, seen) {
				return true
			}
		}
		return false
	default:
		return true
	}
}

// hasNonCoreTag reports whether node carries a YAML tag other than one of
// the core tags the parser assigns during its own default resolution
// (e.g. "!!str", "!!seq", "!!map", or "" for an as-yet-unresolved node). A
// non-core tag — such as GitLab's `!reference` — means the node's shape
// can't be taken at face value: `!reference [.setup, scaling]` is a
// two-element reference path, not a sequence of two job/stage names, even
// though its Kind is yaml.SequenceNode like an ordinary list.
func hasNonCoreTag(node *yaml.Node) bool {
	switch node.Tag {
	case "", "!!str", "!!seq", "!!map", "!!null", "!!bool", "!!int", "!!float", "!!timestamp", "!!binary", "!!merge":
		return false
	default:
		return true
	}
}

// resolveAlias dereferences a chain of YAML alias nodes, returning the
// first non-alias node encountered, or nil if the chain is cyclic.
func resolveAlias(node *yaml.Node) *yaml.Node {
	seen := make(map[*yaml.Node]bool)
	for node != nil && node.Kind == yaml.AliasNode {
		if seen[node] {
			return nil
		}
		seen[node] = true
		node = node.Alias
	}
	return node
}

// isLiteralScalarValue resolves node to a literal, fully-determined scalar
// value suitable for equality comparison: aliases are dereferenced first,
// and the result must be a plain, untagged scalar. ok is false for
// anything else — an unresolvable/cyclic alias, a non-core-tagged value,
// or a non-scalar value — and also for a scalar whose text contains GitLab
// CI/CD variable or pipeline-input interpolation syntax ($VAR, ${VAR}, or
// $[[ ... ]]): such a value is the unevaluated expression text, not the
// value GitLab will actually substitute at pipeline time, so it can't be
// compared as a literal even though it's a plain, untagged ScalarNode.
//
// Centralizing this check means every site in this file that compares a
// resolved scalar for equality (a job's stage: value, an include mapping's
// local: value) shares one fail-closed definition of "known literal" —
// closing an unproven-scalar shape here closes it everywhere at once,
// instead of requiring a matching fix at each call site individually.
func isLiteralScalarValue(node *yaml.Node) (value string, ok bool) {
	resolved := resolveAlias(node)
	if resolved == nil || resolved.Kind != yaml.ScalarNode || hasNonCoreTag(resolved) {
		return "", false
	}
	if strings.Contains(resolved.Value, "$") {
		return "", false
	}
	return resolved.Value, true
}

// extendsNames returns the job/template names referenced by an extends:
// value, which GitLab allows as either a single scalar or a sequence, and
// reports whether the value's shape could be fully resolved. The value
// itself, and each item when it's a sequence, is resolved via
// isLiteralScalarValue rather than a bare resolveAlias/Kind check: that
// centralizes alias dereferencing, the non-core-tag guard (so GitLab's
// `extends: !reference [.setup, scaling]` — a SequenceNode shape identical
// to a two-name extends list, but a reference path rather than job/template
// names — is treated as unresolvable rather than parsed as one), and the
// GitLab CI/CD variable/pipeline-input interpolation guard ($VAR, ${VAR},
// $[[ ... ]]) shared with the stage:/include local: call sites. Without the
// interpolation guard, `extends: $[[ inputs.template ]]` would be treated
// as literally extending a template named "$[[ inputs.template ]]" — a
// name no job actually has — silently missing the real (possibly
// stage-carrying) target instead of failing closed. ok is false when the
// value, or any item within it, isn't a fully-literal scalar by that
// definition, meaning the effective extends target(s) couldn't be
// determined.
func extendsNames(node *yaml.Node) (names []string, ok bool) {
	if value, literalOK := isLiteralScalarValue(node); literalOK {
		return []string{value}, true
	}
	resolved := resolveAlias(node)
	if resolved == nil || hasNonCoreTag(resolved) || resolved.Kind != yaml.SequenceNode {
		return nil, false
	}
	names = make([]string, 0, len(resolved.Content))
	for _, item := range resolved.Content {
		value, itemOK := isLiteralScalarValue(item)
		if !itemOK {
			return nil, false
		}
		names = append(names, value)
	}
	return names, true
}

// HasFullsendEntries reports whether existing .gitlab-ci.yml content
// already contains all fullsend CI entries. It performs semantic drift
// detection by checking:
//
//  1. include: contains the fullsend-pipeline.yml entry
//  2. If stages: exists, it contains poll, agent
//     (if no stages: key, the included pipeline provides them).
//     The obsolete "dispatch" stage is not required (#7337).
//  3. If workflow: exists, it must have a rules: sequence containing
//     fullsend's if: conditions. If workflow: exists without
//     rules:, that is drift — MergeGitLabCI would add them.
//     (if no workflow: block at all, fullsend's jobs self-filter)
//
// Used by the installer to skip unnecessary .gitlab-ci.yml writes when
// all entries are already present, avoiding YAML formatting churn.
func HasFullsendEntries(existing []byte) bool {
	if len(bytes.TrimSpace(existing)) == 0 {
		return false
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return false
	}

	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return false
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return false
	}

	// 1. The include: key must exist and contain fullsend-pipeline.yml.
	includeVal := findMappingValue(root, "include")
	if includeVal == nil {
		return false
	}
	if includeVal.Kind == yaml.SequenceNode {
		if !slices.ContainsFunc(includeVal.Content, isFullsendPipelineInclude) {
			return false
		}
	} else if !isFullsendPipelineInclude(includeVal) {
		return false
	}

	// 2. If stages: exists, it must contain all fullsend stages.
	stagesVal := findMappingValue(root, "stages")
	if stagesVal != nil && stagesVal.Kind == yaml.SequenceNode {
		existingStages := make(map[string]bool)
		for _, item := range stagesVal.Content {
			if item.Kind == yaml.ScalarNode {
				existingStages[item.Value] = true
			}
		}
		for _, stage := range fullsendStages {
			if !existingStages[stage] {
				return false
			}
		}
	}

	// 3. If workflow: exists, rules: must be present and contain
	//    fullsend's if: conditions. A workflow: block without rules:
	//    is drift — MergeGitLabCI would add them.
	workflowVal := findMappingValue(root, "workflow")
	if workflowVal != nil && workflowVal.Kind == yaml.MappingNode {
		rulesVal := findMappingValue(workflowVal, "rules")
		if rulesVal == nil || rulesVal.Kind != yaml.SequenceNode {
			// workflow: exists but has no rules: sequence —
			// MergeGitLabCI would add rules here.
			return false
		}
		existingRules := make(map[string]bool)
		for _, item := range rulesVal.Content {
			if item.Kind == yaml.MappingNode {
				if v := findMappingValue(item, "if"); v != nil {
					existingRules[v.Value] = true
				}
			}
		}
		for _, r := range fullsendWorkflowRules {
			if !existingRules[r.If] {
				return false
			}
		}
	}

	return true
}

// MergeGitLabCI merges fullsend's CI configuration into an existing
// .gitlab-ci.yml. It uses yaml.v3's Node API to preserve comments and
// formatting in the existing file.
//
// The merge performs up to three operations:
//  1. Appends an include entry for .gitlab/ci/fullsend-pipeline.yml
//     (skipped if already present)
//  2. Appends fullsend's current stages (poll, agent) to the
//     existing stages: array, deduplicating if already present.
//     Skipped when no stages: key exists. Does not add the obsolete
//     "dispatch" stage (#7337).
//  3. When a workflow: block already exists, merges workflow:rules
//     entries (deduplicates by if: condition) and sets
//     auto_cancel.on_new_commit: none if not present. When no
//     workflow: block exists, it is left absent so the repo's
//     push-triggered pipelines are not disrupted.
//
// When existing is nil or empty, returns a minimal .gitlab-ci.yml with
// just the fullsend include and workflow block.
func MergeGitLabCI(existing []byte) ([]byte, error) {
	if len(bytes.TrimSpace(existing)) == 0 {
		return newGitLabCI()
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return nil, fmt.Errorf("parsing existing .gitlab-ci.yml: %w", err)
	}

	// yaml.Unmarshal wraps content in a Document node.
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return newGitLabCI()
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return newGitLabCI()
	}

	if err := mergeInclude(root); err != nil {
		return nil, err
	}
	mergeStages(root)
	if err := mergeWorkflow(root); err != nil {
		return nil, err
	}

	return marshalNode(&doc)
}

// UnmergeGitLabCI removes fullsend's CI configuration from a
// .gitlab-ci.yml. It removes the fullsend pipeline include entry and
// the fullsend workflow:rules entries. Returns the cleaned YAML, or nil
// if the file has no remaining meaningful content.
func UnmergeGitLabCI(existing []byte) ([]byte, error) {
	if len(bytes.TrimSpace(existing)) == 0 {
		return nil, nil
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return nil, fmt.Errorf("parsing .gitlab-ci.yml: %w", err)
	}

	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return nil, nil
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return nil, nil
	}

	removeInclude(root)
	removeStages(root)
	removeWorkflowRules(root)

	// If the root mapping is empty after cleanup, the file has no
	// remaining content and should be deleted entirely.
	if len(root.Content) == 0 {
		return nil, nil
	}

	return marshalNode(&doc)
}

// newGitLabCI returns a minimal .gitlab-ci.yml for a repo that has no
// existing CI config. This matches the embedded scaffold template.
//
// Note: newGitLabCI generates a workflow.name field, but MergeGitLabCI
// intentionally does not add workflow.name when merging into an existing
// file. New repos get a descriptive workflow name; existing repos keep
// whatever name they already have (or none). This avoids overwriting
// user-chosen pipeline names.
func newGitLabCI() ([]byte, error) {
	content := `---
include:
  - local: '.gitlab/ci/fullsend-pipeline.yml'

workflow:
  name: 'fullsend $CI_PIPELINE_SOURCE $STAGE $RESOURCE_KEY'
  auto_cancel:
    on_new_commit: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "api" && $CI_COMMIT_REF_PROTECTED == "true" && $STAGE
`
	return []byte(content), nil
}

// mergeInclude ensures the include: sequence contains an entry for
// the fullsend pipeline file. If the key doesn't exist, it creates one.
func mergeInclude(root *yaml.Node) error {
	includeVal := findMappingValue(root, "include")
	if includeVal == nil {
		// Create include: key with a sequence containing our entry.
		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: "include", Tag: "!!str"}
		entry := makeIncludeEntry(fullsendPipelineInclude)
		seqNode := &yaml.Node{
			Kind:    yaml.SequenceNode,
			Tag:     "!!seq",
			Content: []*yaml.Node{entry},
		}
		// Prepend include at the top of the mapping.
		root.Content = append([]*yaml.Node{keyNode, seqNode}, root.Content...)
		return nil
	}

	if includeVal.Kind != yaml.SequenceNode {
		// include: might be a single scalar or mapping. Wrap it in a
		// sequence so we can append our entry.
		wrapped := &yaml.Node{}
		*wrapped = *includeVal
		includeVal.Kind = yaml.SequenceNode
		includeVal.Tag = "!!seq"
		includeVal.Value = ""
		includeVal.Content = []*yaml.Node{wrapped}
	}

	// Check if our include is already present.
	if slices.ContainsFunc(includeVal.Content, isFullsendPipelineInclude) {
		return nil // Already present, idempotent.
	}

	// Append our include entry.
	entry := makeIncludeEntry(fullsendPipelineInclude)
	includeVal.Content = append(includeVal.Content, entry)
	return nil
}

// makeIncludeEntry creates a YAML mapping node for {local: '<path>'}.
func makeIncludeEntry(path string) *yaml.Node {
	return &yaml.Node{
		Kind: yaml.MappingNode,
		Tag:  "!!map",
		Content: []*yaml.Node{
			{Kind: yaml.ScalarNode, Value: "local", Tag: "!!str"},
			{Kind: yaml.ScalarNode, Value: path, Tag: "!!str", Style: yaml.SingleQuotedStyle},
		},
	}
}

// includeMappingAllowedKeys are the only keys, besides "local", that
// isFullsendPipelineInclude tolerates inside an include-mapping item
// without failing closed. GitLab supports several other include-location
// keys on the same mapping form ("<<" merge, "file", "project", "remote",
// "template", "component") that name a different include entirely — a
// mapping combining one of those with "local:" can't be trusted to
// resolve to the fullsend include and nothing else — so anything not in
// this allowlist is treated the same as an unclassifiable key.
var includeMappingAllowedKeys = map[string]bool{
	"local":     true,
	"rules":     true,
	"inputs":    true,
	"integrity": true,
}

// isFullsendPipelineInclude checks whether a YAML node is an include
// entry pointing to the fullsend pipeline file.
//
// The mapping form (`{local: ...}`) walks every key/value pair rather than
// stopping at the first "local" match: gopkg.in/yaml.v3 preserves
// duplicate mapping keys as separate Content pairs instead of collapsing
// them, and GitLab/Psych is last-wins, so `{local: fullsend-pipeline.yml,
// local: other.yml}` would otherwise be misclassified as the fullsend
// include by a first-match check even though the second, real value wins.
// Key classification is delegated to classifyTopLevelKey (the same
// alias-resolving, tag-checking classifier used for top-level and job
// keys) so an alias-keyed or non-core-tagged key here can't be silently
// treated as an ordinary "local" key. A key outside includeMappingAllowedKeys
// — including one carrying interpolation syntax that might evaluate to
// "local" or another location key at pipeline time, see
// hasInterpolationSyntax — is treated the same as unclassifiable rather
// than silently skipped via continue: it might be another include-location
// key (or a duplicate "local") this check would otherwise miss. A
// duplicated "local" key, an unclassifiable key, and a not-allowlisted key
// all fail closed by returning false — treat this item as not (confirmed
// as) the fullsend pipeline include — since which value GitLab would
// actually resolve to can't be determined with confidence.
func isFullsendPipelineInclude(node *yaml.Node) bool {
	if node.Kind == yaml.ScalarNode {
		return node.Value == fullsendPipelineInclude
	}
	if node.Kind != yaml.MappingNode {
		return false
	}
	localCount := 0
	isFullsend := false
	for i := 0; i+1 < len(node.Content); i += 2 {
		name, ok := classifyTopLevelKey(node.Content[i])
		if !ok || hasInterpolationSyntax(name) || !includeMappingAllowedKeys[name] {
			// An unclassifiable key (an alias, a non-core-tagged key, or a
			// non-scalar key), a key carrying interpolation syntax, or a
			// key that isn't a known-safe include-mapping key can't be
			// ruled out as another "local" occurrence or a different
			// include-location key entirely. Fail closed.
			return false
		}
		if name != "local" {
			continue
		}
		localCount++
		value, ok := isLiteralScalarValue(node.Content[i+1])
		isFullsend = ok && value == fullsendPipelineInclude
	}
	if localCount > 1 {
		return false
	}
	return isFullsend
}

// mergeStages appends fullsend's stages to an existing stages: array,
// deduplicating entries that are already present. When no stages: key
// exists, the function is a no-op — the included pipeline file's
// stages will be used by GitLab automatically.
func mergeStages(root *yaml.Node) {
	stagesVal := findMappingValue(root, "stages")
	if stagesVal == nil || stagesVal.Kind != yaml.SequenceNode {
		return
	}

	// Collect existing stage names for deduplication.
	existing := make(map[string]bool)
	for _, item := range stagesVal.Content {
		if item.Kind == yaml.ScalarNode {
			existing[item.Value] = true
		}
	}

	// Append missing fullsend stages.
	for _, stage := range fullsendStages {
		if !existing[stage] {
			stagesVal.Content = append(stagesVal.Content, &yaml.Node{
				Kind:  yaml.ScalarNode,
				Value: stage,
				Tag:   "!!str",
			})
		}
	}
}

// mergeWorkflow ensures an existing workflow: block contains fullsend's
// rules and auto_cancel settings. When no workflow: block exists, it is
// left absent — fullsend's jobs have their own rules: that self-filter
// by pipeline source, and creating a workflow: block would gate all
// pipelines to only fullsend's sources, breaking push-triggered CI.
func mergeWorkflow(root *yaml.Node) error {
	workflowVal := findMappingValue(root, "workflow")
	if workflowVal == nil {
		// No existing workflow block — leave it absent so the repo's
		// push-triggered pipelines continue to run.
		return nil
	}

	if workflowVal.Kind != yaml.MappingNode {
		return fmt.Errorf("workflow: is not a mapping")
	}

	// Ensure auto_cancel.on_new_commit: none is set.
	mergeAutoCancel(workflowVal)

	// Merge rules.
	mergeWorkflowRules(workflowVal)

	return nil
}

// mergeAutoCancel ensures workflow.auto_cancel.on_new_commit: none.
func mergeAutoCancel(workflow *yaml.Node) {
	acVal := findMappingValue(workflow, "auto_cancel")
	if acVal == nil {
		// Create auto_cancel block.
		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: "auto_cancel", Tag: "!!str"}
		valNode := &yaml.Node{
			Kind: yaml.MappingNode,
			Tag:  "!!map",
			Content: []*yaml.Node{
				{Kind: yaml.ScalarNode, Value: "on_new_commit", Tag: "!!str"},
				{Kind: yaml.ScalarNode, Value: "none", Tag: "!!str"},
			},
		}
		workflow.Content = append(workflow.Content, keyNode, valNode)
		return
	}

	if acVal.Kind != yaml.MappingNode {
		return
	}

	oncVal := findMappingValue(acVal, "on_new_commit")
	if oncVal == nil {
		acVal.Content = append(acVal.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "on_new_commit", Tag: "!!str"},
			&yaml.Node{Kind: yaml.ScalarNode, Value: "none", Tag: "!!str"},
		)
	}
	// If on_new_commit exists, leave the user's value alone.
}

// mergeWorkflowRules appends fullsend's rules to workflow.rules,
// deduplicating by if: condition.
func mergeWorkflowRules(workflow *yaml.Node) {
	rulesVal := findMappingValue(workflow, "rules")
	if rulesVal == nil {
		// Create rules sequence.
		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: "rules", Tag: "!!str"}
		seqNode := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		for _, r := range fullsendWorkflowRules {
			seqNode.Content = append(seqNode.Content, makeRuleNode(r))
		}
		workflow.Content = append(workflow.Content, keyNode, seqNode)
		return
	}

	if rulesVal.Kind != yaml.SequenceNode {
		return
	}

	// Collect existing if: conditions for deduplication.
	existing := make(map[string]bool)
	for _, item := range rulesVal.Content {
		if item.Kind == yaml.MappingNode {
			if v := findMappingValue(item, "if"); v != nil {
				existing[v.Value] = true
			}
		}
	}

	// Append missing rules.
	for _, r := range fullsendWorkflowRules {
		if !existing[r.If] {
			rulesVal.Content = append(rulesVal.Content, makeRuleNode(r))
		}
	}
}

// makeRuleNode creates a YAML mapping node for a workflow rule.
func makeRuleNode(r workflowRule) *yaml.Node {
	return &yaml.Node{
		Kind: yaml.MappingNode,
		Tag:  "!!map",
		Content: []*yaml.Node{
			{Kind: yaml.ScalarNode, Value: "if", Tag: "!!str"},
			{Kind: yaml.ScalarNode, Value: r.If, Tag: "!!str"},
		},
	}
}

// removeInclude removes the fullsend pipeline include entry from
// the include: sequence. If the sequence becomes empty, removes the
// include: key entirely.
func removeInclude(root *yaml.Node) {
	includeIdx := findMappingKeyIndex(root, "include")
	if includeIdx < 0 {
		return
	}
	includeVal := root.Content[includeIdx+1]

	if includeVal.Kind == yaml.SequenceNode {
		var kept []*yaml.Node
		for _, item := range includeVal.Content {
			if !isFullsendPipelineInclude(item) {
				kept = append(kept, item)
			}
		}
		if len(kept) == 0 {
			// Remove the entire include: key.
			root.Content = append(root.Content[:includeIdx], root.Content[includeIdx+2:]...)
		} else {
			includeVal.Content = kept
		}
	} else if isFullsendPipelineInclude(includeVal) {
		root.Content = append(root.Content[:includeIdx], root.Content[includeIdx+2:]...)
	}
}

// removeStages removes fullsend's stages from the stages: array. If
// the array becomes empty, removes the stages: key entirely.
func removeStages(root *yaml.Node) {
	stagesIdx := findMappingKeyIndex(root, "stages")
	if stagesIdx < 0 {
		return
	}
	stagesVal := root.Content[stagesIdx+1]
	if stagesVal.Kind != yaml.SequenceNode {
		return
	}

	fsStages := make(map[string]bool, len(fullsendStages)+len(obsoleteGitLabStages))
	for _, stage := range fullsendStages {
		fsStages[stage] = true
	}
	// Uninstall still strips stages previous versions installed, so a
	// repo enrolled before #7337 does not keep a leftover dispatch stage.
	for _, stage := range obsoleteGitLabStages {
		fsStages[stage] = true
	}

	var kept []*yaml.Node
	for _, item := range stagesVal.Content {
		if item.Kind == yaml.ScalarNode && fsStages[item.Value] {
			continue
		}
		kept = append(kept, item)
	}

	if len(kept) == 0 {
		root.Content = append(root.Content[:stagesIdx], root.Content[stagesIdx+2:]...)
	} else {
		stagesVal.Content = kept
	}
}

// removeWorkflowRules removes fullsend's workflow:rules entries. If
// the workflow block has no remaining keys, removes it entirely.
func removeWorkflowRules(root *yaml.Node) {
	wfIdx := findMappingKeyIndex(root, "workflow")
	if wfIdx < 0 {
		return
	}
	workflowVal := root.Content[wfIdx+1]
	if workflowVal.Kind != yaml.MappingNode {
		return
	}

	// Build a set of fullsend rule conditions for matching.
	fsRules := make(map[string]bool)
	for _, r := range unmergeWorkflowRules {
		fsRules[r.If] = true
	}
	// When the block carries fullsend's provenance marker (workflow.name),
	// fullsend also owns any obsolete rule it installed in an earlier
	// version, so remove those too — otherwise a fresh-install uninstall
	// leaves the orphaned merge_request_event rule behind, producing the
	// empty MR pipelines #7322 set out to eliminate. Without the marker the
	// obsolete rule is indistinguishable from a repo's own MR gate and is
	// left in place (see unmergeWorkflowRules and StripObsoleteGitLabWorkflowRules,
	// which gate on the same ownership check).
	if gitlabCIWorkflowIsFullsendOwned(workflowVal) {
		for _, r := range obsoleteGitLabWorkflowRules {
			fsRules[r.If] = true
		}
	}

	// Remove matching rules from workflow.rules.
	rulesIdx := findMappingKeyIndex(workflowVal, "rules")
	if rulesIdx >= 0 {
		rulesVal := workflowVal.Content[rulesIdx+1]
		if rulesVal.Kind == yaml.SequenceNode {
			var kept []*yaml.Node
			for _, item := range rulesVal.Content {
				if item.Kind == yaml.MappingNode {
					if v := findMappingValue(item, "if"); v != nil && fsRules[v.Value] {
						continue
					}
				}
				kept = append(kept, item)
			}
			if len(kept) == 0 {
				// Remove rules: key entirely.
				workflowVal.Content = append(
					workflowVal.Content[:rulesIdx],
					workflowVal.Content[rulesIdx+2:]...)
			} else {
				rulesVal.Content = kept
			}
		}
	}

	// Remove workflow.name if it matches the fullsend pattern.
	nameIdx := findMappingKeyIndex(workflowVal, "name")
	if nameIdx >= 0 {
		nameVal := workflowVal.Content[nameIdx+1]
		if strings.HasPrefix(nameVal.Value, fullsendWorkflowNamePrefix) {
			workflowVal.Content = append(
				workflowVal.Content[:nameIdx],
				workflowVal.Content[nameIdx+2:]...)
		}
	}

	// Remove auto_cancel.on_new_commit if it's "none" (fullsend's value).
	acIdx := findMappingKeyIndex(workflowVal, "auto_cancel")
	if acIdx >= 0 {
		acVal := workflowVal.Content[acIdx+1]
		if acVal.Kind == yaml.MappingNode {
			oncIdx := findMappingKeyIndex(acVal, "on_new_commit")
			if oncIdx >= 0 && acVal.Content[oncIdx+1].Value == "none" {
				acVal.Content = append(acVal.Content[:oncIdx], acVal.Content[oncIdx+2:]...)
			}
			if len(acVal.Content) == 0 {
				workflowVal.Content = append(
					workflowVal.Content[:acIdx],
					workflowVal.Content[acIdx+2:]...)
			}
		}
	}

	// If workflow block is empty, remove it.
	if len(workflowVal.Content) == 0 {
		root.Content = append(root.Content[:wfIdx], root.Content[wfIdx+2:]...)
	}
}

// findMappingValue returns the value node for a key in a mapping node,
// or nil if not found.
func findMappingValue(mapping *yaml.Node, key string) *yaml.Node {
	idx := findMappingKeyIndex(mapping, key)
	if idx < 0 {
		return nil
	}
	return mapping.Content[idx+1]
}

// findMappingKeyIndex returns the index of a key in a mapping node's
// Content slice, or -1 if not found.
func findMappingKeyIndex(mapping *yaml.Node, key string) int {
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return i
		}
	}
	return -1
}

// marshalNode marshals a yaml.Node tree back to YAML bytes.
func marshalNode(doc *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("marshaling YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing YAML encoder: %w", err)
	}
	return buf.Bytes(), nil
}

// unmergeGitLabRootCI fetches the existing .gitlab-ci.yml from the repo
// and removes fullsend's entries. Returns the cleaned content, or nil
// if the file should be deleted entirely.
func unmergeGitLabRootCI(ctx context.Context, client forge.Client, owner, repo string) ([]byte, error) {
	existing, err := client.GetFileContent(ctx, owner, repo, ".gitlab-ci.yml")
	if err != nil {
		if forge.IsNotFound(err) {
			return nil, nil // Nothing to clean up.
		}
		return nil, fmt.Errorf("reading .gitlab-ci.yml for cleanup: %w", err)
	}
	return UnmergeGitLabCI(existing)
}

// gitlabPipelineWrapperStillIncludesDispatch fetches the on-repo fullsend
// pipeline wrapper (fullsendPipelineInclude) and reports whether it still
// carries a local include entry for fullsendDispatchInclude.
//
// StripObsoleteGitLabStages only ever sees the root .gitlab-ci.yml: its
// include-ownership gate confirms the root file's own "include:" entry
// names the fullsend pipeline wrapper, but it has no way to confirm what
// that wrapper itself pulls in. fullsend versions before #7322 shipped a
// wrapper that included fullsendDispatchInclude, which defined the native
// merge_request_event dispatch job on the "dispatch" stage; #7322 dropped
// that include from the wrapper template, and #7337 dropped the stage
// from the required set. A repo enrolled (or last upgraded) before #7322
// can still have the old, on-repo wrapper — with the dispatch include
// still present — even on a converge run using a post-#7337 CLI. Without
// this check, convergeGitLabRootCIFiles could strip the "dispatch" stage
// from the root file's stages: while the still-included dispatch job
// keeps running on it, which GitLab then rejects at pipeline time.
//
// The wrapper is a fullsend-owned file ("do not edit it directly" — see
// internal/scaffold/fullsend-repo-gitlab/.gitlab/ci/fullsend-pipeline.yml)
// with an intentionally narrow, known shape, so a direct include: scan is
// proportionate here rather than the full alias/tag-resolving machinery
// StripObsoleteGitLabStages applies to the arbitrary, user-owned root
// file.
//
// Any outcome other than "confirmed absent" fails closed (returns true):
// a read error other than not-found, a parse error, an unexpected
// document shape, or the include entry actually being present. A 404
// reading the wrapper is treated as confirmed absent — there is no
// on-repo wrapper file to pull in the obsolete include.
func gitlabPipelineWrapperStillIncludesDispatch(ctx context.Context, client forge.Client, owner, repo string) (bool, error) {
	content, err := client.GetFileContent(ctx, owner, repo, fullsendPipelineInclude)
	if err != nil {
		if forge.IsNotFound(err) {
			return false, nil
		}
		return true, fmt.Errorf("reading %s: %w", fullsendPipelineInclude, err)
	}
	if len(bytes.TrimSpace(content)) == 0 {
		return false, nil
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(content, &doc); err != nil {
		return true, fmt.Errorf("parsing %s: %w", fullsendPipelineInclude, err)
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return true, nil
	}
	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return true, nil
	}

	includeVal := findMappingValue(root, "include")
	if includeVal == nil {
		return false, nil
	}
	items := []*yaml.Node{includeVal}
	if includeVal.Kind == yaml.SequenceNode {
		items = includeVal.Content
	}
	for _, item := range items {
		if item.Kind == yaml.ScalarNode && item.Value == fullsendDispatchInclude {
			return true, nil
		}
		if item.Kind == yaml.MappingNode {
			if local := findMappingValue(item, "local"); local != nil &&
				local.Kind == yaml.ScalarNode && local.Value == fullsendDispatchInclude {
				return true, nil
			}
		}
	}
	return false, nil
}
