package repos

import (
	"bytes"
	"context"
	"fmt"
	"slices"
	"strings"

	"github.com/fullsend-ai/fullsend/internal/forge"
	"gopkg.in/yaml.v3"
)

// fullsendPipelineInclude is the include entry that points to the
// fullsend-owned pipeline wrapper file.
const fullsendPipelineInclude = ".gitlab/ci/fullsend-pipeline.yml"

// fullsendWorkflowNamePrefix is the prefix of the workflow.name value
// generated by newGitLabCI. Used during unmerge to remove the
// fullsend-specific workflow name.
const fullsendWorkflowNamePrefix = "fullsend "

// fullsendStages are the pipeline stages that fullsend's jobs use.
// GitLab's deep merge only applies to hash maps — stages: is a YAML
// array and is overwritten, not merged (see gitlab-org/gitlab#29980).
// When the root .gitlab-ci.yml already defines stages:, the included
// file's stages are silently dropped, so these must be added directly
// to the root file.
var fullsendStages = []string{"dispatch", "poll", "agent"}

// fullsendWorkflowRules are the workflow:rules entries that fullsend
// requires in the root .gitlab-ci.yml. GitLab does not merge workflow:
// definitions across includes, so these must be in the root file.
var fullsendWorkflowRules = []workflowRule{
	{If: `$CI_PIPELINE_SOURCE == "merge_request_event"`},
	{If: `$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true"`},
	{If: `$CI_PIPELINE_SOURCE == "api" && $CI_COMMIT_REF_PROTECTED == "true" && $STAGE`},
}

// workflowRule represents a single GitLab CI workflow:rules entry
// identified by its if: condition.
type workflowRule struct {
	If string
}

// HasFullsendEntries reports whether existing .gitlab-ci.yml content
// already contains all fullsend CI entries. It performs semantic drift
// detection by checking:
//
//  1. include: contains the fullsend-pipeline.yml entry
//  2. If stages: exists, it contains dispatch, poll, agent
//     (if no stages: key, the included pipeline provides them)
//  3. If workflow: exists, it must have a rules: sequence containing
//     fullsend's three if: conditions. If workflow: exists without
//     rules:, that is drift — MergeGitLabCI would add them.
//     (if no workflow: block at all, fullsend's jobs self-filter)
//
// Used by the installer to skip unnecessary .gitlab-ci.yml writes when
// all entries are already present, avoiding YAML formatting churn.
func HasFullsendEntries(existing []byte) bool {
	if len(bytes.TrimSpace(existing)) == 0 {
		return false
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return false
	}

	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return false
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return false
	}

	// 1. The include: key must exist and contain fullsend-pipeline.yml.
	includeVal := findMappingValue(root, "include")
	if includeVal == nil {
		return false
	}
	if includeVal.Kind == yaml.SequenceNode {
		if !slices.ContainsFunc(includeVal.Content, isFullsendPipelineInclude) {
			return false
		}
	} else if !isFullsendPipelineInclude(includeVal) {
		return false
	}

	// 2. If stages: exists, it must contain all fullsend stages.
	stagesVal := findMappingValue(root, "stages")
	if stagesVal != nil && stagesVal.Kind == yaml.SequenceNode {
		existingStages := make(map[string]bool)
		for _, item := range stagesVal.Content {
			if item.Kind == yaml.ScalarNode {
				existingStages[item.Value] = true
			}
		}
		for _, stage := range fullsendStages {
			if !existingStages[stage] {
				return false
			}
		}
	}

	// 3. If workflow: exists, rules: must be present and contain
	//    fullsend's if: conditions. A workflow: block without rules:
	//    is drift — MergeGitLabCI would add them.
	workflowVal := findMappingValue(root, "workflow")
	if workflowVal != nil && workflowVal.Kind == yaml.MappingNode {
		rulesVal := findMappingValue(workflowVal, "rules")
		if rulesVal == nil || rulesVal.Kind != yaml.SequenceNode {
			// workflow: exists but has no rules: sequence —
			// MergeGitLabCI would add rules here.
			return false
		}
		existingRules := make(map[string]bool)
		for _, item := range rulesVal.Content {
			if item.Kind == yaml.MappingNode {
				if v := findMappingValue(item, "if"); v != nil {
					existingRules[v.Value] = true
				}
			}
		}
		for _, r := range fullsendWorkflowRules {
			if !existingRules[r.If] {
				return false
			}
		}
	}

	return true
}

// MergeGitLabCI merges fullsend's CI configuration into an existing
// .gitlab-ci.yml. It uses yaml.v3's Node API to preserve comments and
// formatting in the existing file.
//
// The merge performs up to three operations:
//  1. Appends an include entry for .gitlab/ci/fullsend-pipeline.yml
//     (skipped if already present)
//  2. Appends fullsend's stages (dispatch, poll, agent) to the
//     existing stages: array, deduplicating if already present.
//     Skipped when no stages: key exists.
//  3. When a workflow: block already exists, merges workflow:rules
//     entries (deduplicates by if: condition) and sets
//     auto_cancel.on_new_commit: none if not present. When no
//     workflow: block exists, it is left absent so the repo's
//     push-triggered pipelines are not disrupted.
//
// When existing is nil or empty, returns a minimal .gitlab-ci.yml with
// just the fullsend include and workflow block.
func MergeGitLabCI(existing []byte) ([]byte, error) {
	if len(bytes.TrimSpace(existing)) == 0 {
		return newGitLabCI()
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return nil, fmt.Errorf("parsing existing .gitlab-ci.yml: %w", err)
	}

	// yaml.Unmarshal wraps content in a Document node.
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return newGitLabCI()
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return newGitLabCI()
	}

	if err := mergeInclude(root); err != nil {
		return nil, err
	}
	mergeStages(root)
	if err := mergeWorkflow(root); err != nil {
		return nil, err
	}

	return marshalNode(&doc)
}

// UnmergeGitLabCI removes fullsend's CI configuration from a
// .gitlab-ci.yml. It removes the fullsend pipeline include entry and
// the fullsend workflow:rules entries. Returns the cleaned YAML, or nil
// if the file has no remaining meaningful content.
func UnmergeGitLabCI(existing []byte) ([]byte, error) {
	if len(bytes.TrimSpace(existing)) == 0 {
		return nil, nil
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return nil, fmt.Errorf("parsing .gitlab-ci.yml: %w", err)
	}

	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return nil, nil
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return nil, nil
	}

	removeInclude(root)
	removeStages(root)
	removeWorkflowRules(root)

	// If the root mapping is empty after cleanup, the file has no
	// remaining content and should be deleted entirely.
	if len(root.Content) == 0 {
		return nil, nil
	}

	return marshalNode(&doc)
}

// newGitLabCI returns a minimal .gitlab-ci.yml for a repo that has no
// existing CI config. This matches the embedded scaffold template.
//
// Note: newGitLabCI generates a workflow.name field, but MergeGitLabCI
// intentionally does not add workflow.name when merging into an existing
// file. New repos get a descriptive workflow name; existing repos keep
// whatever name they already have (or none). This avoids overwriting
// user-chosen pipeline names.
func newGitLabCI() ([]byte, error) {
	content := `---
include:
  - local: '.gitlab/ci/fullsend-pipeline.yml'

workflow:
  name: 'fullsend $CI_PIPELINE_SOURCE $STAGE $RESOURCE_KEY'
  auto_cancel:
    on_new_commit: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "api" && $CI_COMMIT_REF_PROTECTED == "true" && $STAGE
`
	return []byte(content), nil
}

// mergeInclude ensures the include: sequence contains an entry for
// the fullsend pipeline file. If the key doesn't exist, it creates one.
func mergeInclude(root *yaml.Node) error {
	includeVal := findMappingValue(root, "include")
	if includeVal == nil {
		// Create include: key with a sequence containing our entry.
		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: "include", Tag: "!!str"}
		entry := makeIncludeEntry(fullsendPipelineInclude)
		seqNode := &yaml.Node{
			Kind:    yaml.SequenceNode,
			Tag:     "!!seq",
			Content: []*yaml.Node{entry},
		}
		// Prepend include at the top of the mapping.
		root.Content = append([]*yaml.Node{keyNode, seqNode}, root.Content...)
		return nil
	}

	if includeVal.Kind != yaml.SequenceNode {
		// include: might be a single scalar or mapping. Wrap it in a
		// sequence so we can append our entry.
		wrapped := &yaml.Node{}
		*wrapped = *includeVal
		includeVal.Kind = yaml.SequenceNode
		includeVal.Tag = "!!seq"
		includeVal.Value = ""
		includeVal.Content = []*yaml.Node{wrapped}
	}

	// Check if our include is already present.
	if slices.ContainsFunc(includeVal.Content, isFullsendPipelineInclude) {
		return nil // Already present, idempotent.
	}

	// Append our include entry.
	entry := makeIncludeEntry(fullsendPipelineInclude)
	includeVal.Content = append(includeVal.Content, entry)
	return nil
}

// makeIncludeEntry creates a YAML mapping node for {local: '<path>'}.
func makeIncludeEntry(path string) *yaml.Node {
	return &yaml.Node{
		Kind: yaml.MappingNode,
		Tag:  "!!map",
		Content: []*yaml.Node{
			{Kind: yaml.ScalarNode, Value: "local", Tag: "!!str"},
			{Kind: yaml.ScalarNode, Value: path, Tag: "!!str", Style: yaml.SingleQuotedStyle},
		},
	}
}

// isFullsendPipelineInclude checks whether a YAML node is an include
// entry pointing to the fullsend pipeline file.
func isFullsendPipelineInclude(node *yaml.Node) bool {
	if node.Kind == yaml.ScalarNode {
		return node.Value == fullsendPipelineInclude
	}
	if node.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(node.Content); i += 2 {
			if node.Content[i].Value == "local" &&
				node.Content[i+1].Value == fullsendPipelineInclude {
				return true
			}
		}
	}
	return false
}

// mergeStages appends fullsend's stages to an existing stages: array,
// deduplicating entries that are already present. When no stages: key
// exists, the function is a no-op — the included pipeline file's
// stages will be used by GitLab automatically.
func mergeStages(root *yaml.Node) {
	stagesVal := findMappingValue(root, "stages")
	if stagesVal == nil || stagesVal.Kind != yaml.SequenceNode {
		return
	}

	// Collect existing stage names for deduplication.
	existing := make(map[string]bool)
	for _, item := range stagesVal.Content {
		if item.Kind == yaml.ScalarNode {
			existing[item.Value] = true
		}
	}

	// Append missing fullsend stages.
	for _, stage := range fullsendStages {
		if !existing[stage] {
			stagesVal.Content = append(stagesVal.Content, &yaml.Node{
				Kind:  yaml.ScalarNode,
				Value: stage,
				Tag:   "!!str",
			})
		}
	}
}

// mergeWorkflow ensures an existing workflow: block contains fullsend's
// rules and auto_cancel settings. When no workflow: block exists, it is
// left absent — fullsend's jobs have their own rules: that self-filter
// by pipeline source, and creating a workflow: block would gate all
// pipelines to only fullsend's sources, breaking push-triggered CI.
func mergeWorkflow(root *yaml.Node) error {
	workflowVal := findMappingValue(root, "workflow")
	if workflowVal == nil {
		// No existing workflow block — leave it absent so the repo's
		// push-triggered pipelines continue to run.
		return nil
	}

	if workflowVal.Kind != yaml.MappingNode {
		return fmt.Errorf("workflow: is not a mapping")
	}

	// Ensure auto_cancel.on_new_commit: none is set.
	mergeAutoCancel(workflowVal)

	// Merge rules.
	mergeWorkflowRules(workflowVal)

	return nil
}

// mergeAutoCancel ensures workflow.auto_cancel.on_new_commit: none.
func mergeAutoCancel(workflow *yaml.Node) {
	acVal := findMappingValue(workflow, "auto_cancel")
	if acVal == nil {
		// Create auto_cancel block.
		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: "auto_cancel", Tag: "!!str"}
		valNode := &yaml.Node{
			Kind: yaml.MappingNode,
			Tag:  "!!map",
			Content: []*yaml.Node{
				{Kind: yaml.ScalarNode, Value: "on_new_commit", Tag: "!!str"},
				{Kind: yaml.ScalarNode, Value: "none", Tag: "!!str"},
			},
		}
		workflow.Content = append(workflow.Content, keyNode, valNode)
		return
	}

	if acVal.Kind != yaml.MappingNode {
		return
	}

	oncVal := findMappingValue(acVal, "on_new_commit")
	if oncVal == nil {
		acVal.Content = append(acVal.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "on_new_commit", Tag: "!!str"},
			&yaml.Node{Kind: yaml.ScalarNode, Value: "none", Tag: "!!str"},
		)
	}
	// If on_new_commit exists, leave the user's value alone.
}

// mergeWorkflowRules appends fullsend's rules to workflow.rules,
// deduplicating by if: condition.
func mergeWorkflowRules(workflow *yaml.Node) {
	rulesVal := findMappingValue(workflow, "rules")
	if rulesVal == nil {
		// Create rules sequence.
		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: "rules", Tag: "!!str"}
		seqNode := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		for _, r := range fullsendWorkflowRules {
			seqNode.Content = append(seqNode.Content, makeRuleNode(r))
		}
		workflow.Content = append(workflow.Content, keyNode, seqNode)
		return
	}

	if rulesVal.Kind != yaml.SequenceNode {
		return
	}

	// Collect existing if: conditions for deduplication.
	existing := make(map[string]bool)
	for _, item := range rulesVal.Content {
		if item.Kind == yaml.MappingNode {
			if v := findMappingValue(item, "if"); v != nil {
				existing[v.Value] = true
			}
		}
	}

	// Append missing rules.
	for _, r := range fullsendWorkflowRules {
		if !existing[r.If] {
			rulesVal.Content = append(rulesVal.Content, makeRuleNode(r))
		}
	}
}

// makeRuleNode creates a YAML mapping node for a workflow rule.
func makeRuleNode(r workflowRule) *yaml.Node {
	return &yaml.Node{
		Kind: yaml.MappingNode,
		Tag:  "!!map",
		Content: []*yaml.Node{
			{Kind: yaml.ScalarNode, Value: "if", Tag: "!!str"},
			{Kind: yaml.ScalarNode, Value: r.If, Tag: "!!str"},
		},
	}
}

// removeInclude removes the fullsend pipeline include entry from
// the include: sequence. If the sequence becomes empty, removes the
// include: key entirely.
func removeInclude(root *yaml.Node) {
	includeIdx := findMappingKeyIndex(root, "include")
	if includeIdx < 0 {
		return
	}
	includeVal := root.Content[includeIdx+1]

	if includeVal.Kind == yaml.SequenceNode {
		var kept []*yaml.Node
		for _, item := range includeVal.Content {
			if !isFullsendPipelineInclude(item) {
				kept = append(kept, item)
			}
		}
		if len(kept) == 0 {
			// Remove the entire include: key.
			root.Content = append(root.Content[:includeIdx], root.Content[includeIdx+2:]...)
		} else {
			includeVal.Content = kept
		}
	} else if isFullsendPipelineInclude(includeVal) {
		root.Content = append(root.Content[:includeIdx], root.Content[includeIdx+2:]...)
	}
}

// removeStages removes fullsend's stages from the stages: array. If
// the array becomes empty, removes the stages: key entirely.
func removeStages(root *yaml.Node) {
	stagesIdx := findMappingKeyIndex(root, "stages")
	if stagesIdx < 0 {
		return
	}
	stagesVal := root.Content[stagesIdx+1]
	if stagesVal.Kind != yaml.SequenceNode {
		return
	}

	fsStages := make(map[string]bool)
	for _, stage := range fullsendStages {
		fsStages[stage] = true
	}

	var kept []*yaml.Node
	for _, item := range stagesVal.Content {
		if item.Kind == yaml.ScalarNode && fsStages[item.Value] {
			continue
		}
		kept = append(kept, item)
	}

	if len(kept) == 0 {
		root.Content = append(root.Content[:stagesIdx], root.Content[stagesIdx+2:]...)
	} else {
		stagesVal.Content = kept
	}
}

// removeWorkflowRules removes fullsend's workflow:rules entries. If
// the workflow block has no remaining keys, removes it entirely.
func removeWorkflowRules(root *yaml.Node) {
	wfIdx := findMappingKeyIndex(root, "workflow")
	if wfIdx < 0 {
		return
	}
	workflowVal := root.Content[wfIdx+1]
	if workflowVal.Kind != yaml.MappingNode {
		return
	}

	// Build a set of fullsend rule conditions for matching.
	fsRules := make(map[string]bool)
	for _, r := range fullsendWorkflowRules {
		fsRules[r.If] = true
	}

	// Remove matching rules from workflow.rules.
	rulesIdx := findMappingKeyIndex(workflowVal, "rules")
	if rulesIdx >= 0 {
		rulesVal := workflowVal.Content[rulesIdx+1]
		if rulesVal.Kind == yaml.SequenceNode {
			var kept []*yaml.Node
			for _, item := range rulesVal.Content {
				if item.Kind == yaml.MappingNode {
					if v := findMappingValue(item, "if"); v != nil && fsRules[v.Value] {
						continue
					}
				}
				kept = append(kept, item)
			}
			if len(kept) == 0 {
				// Remove rules: key entirely.
				workflowVal.Content = append(
					workflowVal.Content[:rulesIdx],
					workflowVal.Content[rulesIdx+2:]...)
			} else {
				rulesVal.Content = kept
			}
		}
	}

	// Remove workflow.name if it matches the fullsend pattern.
	nameIdx := findMappingKeyIndex(workflowVal, "name")
	if nameIdx >= 0 {
		nameVal := workflowVal.Content[nameIdx+1]
		if strings.HasPrefix(nameVal.Value, fullsendWorkflowNamePrefix) {
			workflowVal.Content = append(
				workflowVal.Content[:nameIdx],
				workflowVal.Content[nameIdx+2:]...)
		}
	}

	// Remove auto_cancel.on_new_commit if it's "none" (fullsend's value).
	acIdx := findMappingKeyIndex(workflowVal, "auto_cancel")
	if acIdx >= 0 {
		acVal := workflowVal.Content[acIdx+1]
		if acVal.Kind == yaml.MappingNode {
			oncIdx := findMappingKeyIndex(acVal, "on_new_commit")
			if oncIdx >= 0 && acVal.Content[oncIdx+1].Value == "none" {
				acVal.Content = append(acVal.Content[:oncIdx], acVal.Content[oncIdx+2:]...)
			}
			if len(acVal.Content) == 0 {
				workflowVal.Content = append(
					workflowVal.Content[:acIdx],
					workflowVal.Content[acIdx+2:]...)
			}
		}
	}

	// If workflow block is empty, remove it.
	if len(workflowVal.Content) == 0 {
		root.Content = append(root.Content[:wfIdx], root.Content[wfIdx+2:]...)
	}
}

// findMappingValue returns the value node for a key in a mapping node,
// or nil if not found.
func findMappingValue(mapping *yaml.Node, key string) *yaml.Node {
	idx := findMappingKeyIndex(mapping, key)
	if idx < 0 {
		return nil
	}
	return mapping.Content[idx+1]
}

// findMappingKeyIndex returns the index of a key in a mapping node's
// Content slice, or -1 if not found.
func findMappingKeyIndex(mapping *yaml.Node, key string) int {
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return i
		}
	}
	return -1
}

// marshalNode marshals a yaml.Node tree back to YAML bytes.
func marshalNode(doc *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("marshaling YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing YAML encoder: %w", err)
	}
	return buf.Bytes(), nil
}

// unmergeGitLabRootCI fetches the existing .gitlab-ci.yml from the repo
// and removes fullsend's entries. Returns the cleaned content, or nil
// if the file should be deleted entirely.
func unmergeGitLabRootCI(ctx context.Context, client forge.Client, owner, repo string) ([]byte, error) {
	existing, err := client.GetFileContent(ctx, owner, repo, ".gitlab-ci.yml")
	if err != nil {
		if forge.IsNotFound(err) {
			return nil, nil // Nothing to clean up.
		}
		return nil, fmt.Errorf("reading .gitlab-ci.yml for cleanup: %w", err)
	}
	return UnmergeGitLabCI(existing)
}
