// Package repos provides reusable per-repo installation logic for fullsend.
// It decouples the core install flow (scaffold commit, variable/secret writes)
// from CLI concerns (prompts, spinners, flag parsing) so that both the
// interactive CLI and future bulk-install commands can share the same logic.
package repos

import (
	"context"
	"fmt"
	"regexp"
	"time"

	"github.com/fullsend-ai/fullsend/internal/config"
	"github.com/fullsend-ai/fullsend/internal/forge"
	"github.com/fullsend-ai/fullsend/internal/maputil"
	"github.com/fullsend-ai/fullsend/internal/scaffold"
)

// WIFProviderPattern validates the full WIF provider resource name format
// required by google-github-actions/auth@v3.
// GCP pool/provider IDs: 4-32 chars, [a-z0-9-], start with letter, no trailing hyphen.
var WIFProviderPattern = regexp.MustCompile(
	`^projects/\d+/locations/global/workloadIdentityPools/[a-z][a-z0-9-]{2,30}[a-z0-9]/providers/[a-z][a-z0-9-]{2,30}[a-z0-9]$`,
)

// InstallConfig is a pure data struct holding all inputs needed for a
// per-repo installation. CLI flags, environment variables, and interactive
// prompts are resolved by the caller before constructing this struct.
type InstallConfig struct {
	Owner string
	Repo  string
	Forge string

	// Roles is the list of agent roles to install (e.g., "triage", "code").
	Roles []string

	MintURL string

	InferenceProject string
	InferenceRegion  string

	// UpstreamRef is the git ref (SHA) used to pin scaffold workflow refs.
	// Empty for dev builds (falls back to config.DefaultUpstreamRef).
	UpstreamRef string
	// UpstreamTag is the version tag corresponding to UpstreamRef (e.g., "v0.42.0").
	UpstreamTag string

	// Skip flags control which install steps are executed. Set by callers
	// that handle specific steps externally (e.g., admin.go handles mint
	// setup before calling Install).
	SkipAppSetup bool

	// SkipScaffoldAndConfig skips scaffold file delivery and variable/secret
	// writes. The caller handles these steps externally (e.g., vendor mode
	// commits scaffold and vendor files together atomically).
	SkipScaffoldAndConfig bool

	// WIFProvider is the pre-computed WIF provider resource name. The caller
	// is responsible for computing or provisioning this value before calling
	// Install. Required unless SkipScaffoldAndConfig is true.
	WIFProvider string

	// PerRepoConfig, when set, overrides the default per-repo config
	// generated by NewPerRepoConfig. Used during migration to carry
	// over org config fields into the per-repo config.
	PerRepoConfig config.PerRepoConfigWriter

	// Runtime, when set, is written as the per-repo `runtime:` of the
	// generated config (`fullsend admin install <owner>/<repo> --runtime`).
	// Empty keeps the code default; ignored when PerRepoConfig is set.
	Runtime string

	VendorBinary bool

	// ReviewAppClientID is the OAuth client ID of the review agent's
	// GitHub App. When set, it is written as the FULLSEND_REVIEW_CLIENT_ID
	// repo variable so that pre-fetch-prior-review.sh can validate
	// provenance of prior review comments.
	ReviewAppClientID string

	// RunnerTags is a list of GitLab CI runner tags to embed in scaffold
	// pipeline YAML so that agent jobs are routed to specific runners.
	RunnerTags []string

	// Direct controls scaffold delivery: true pushes directly to the default
	// branch; false creates a PR.
	Direct bool

	// ReuseSecrets indicates that GCP secrets (FULLSEND_GCP_PROJECT_ID and
	// FULLSEND_GCP_WIF_PROVIDER) already exist on the repo and should not
	// be overwritten. When true, InferenceProject and WIFProvider may be
	// empty and secret writes are skipped.
	ReuseSecrets bool

	// PrebuiltScaffoldFiles, when non-nil, replaces the embedded scaffold
	// template collection. Used when fullsend_ref pins to a version that
	// differs from the running binary, so templates are fetched from the
	// fullsend-ai/fullsend repo at the pinned ref.
	PrebuiltScaffoldFiles scaffold.InstallFiles
}

// InstallResult holds the outcome of a per-repo installation.
type InstallResult struct {
	Owner string
	Repo  string

	Success bool
	Error   error

	// WIFProvider is the WIF provider resource name, either pre-existing
	// (from InstallConfig) or newly provisioned.
	WIFProvider string
}

// ScaffoldCommitFunc delivers scaffold files to a repository and returns
// any error encountered.
//
// The installed parameter indicates whether this repo already had fullsend
// components before this operation (true = upgrade, false = fresh install).
// CLI implementations use this to select the appropriate commit message and
// PR title without making extra API calls.
//
// The CLI layer provides an implementation wrapping layers.CommitScaffoldFiles,
// which adds retry on non-fast-forward errors, branch-protection fallback to
// PR delivery, and fork-based PR support for non-owner users.
type ScaffoldCommitFunc func(ctx context.Context, owner, repo string,
	files []forge.TreeFile, direct bool, installed bool) error

// ProgressFunc is a callback for reporting installation progress. The caller
// maps this to spinner output, structured logs, or whatever UI is appropriate.
//
// Parameters:
//   - repo: the "owner/repo" being installed
//   - phase: a machine-readable phase name (e.g., "scaffold", "vars", "secrets")
//   - message: a human-readable status message
type ProgressFunc func(repo, phase, message string)

// Install performs a per-repo fullsend installation. It generates and commits
// scaffold files, and writes repository
// variables and secrets. The caller is responsible for computing the WIF
// provider resource name (via InstallConfig.WIFProvider) before calling this
// function — GCP provisioning is handled separately by `inference provision`
// and `mint enroll`.
func Install(ctx context.Context, cfg InstallConfig,
	client forge.Client,
	commitScaffold ScaffoldCommitFunc,
	progress ProgressFunc) (*InstallResult, error) {

	if progress == nil {
		progress = func(_, _, _ string) {}
	}

	repoFullName := cfg.Owner + "/" + cfg.Repo
	result := &InstallResult{
		Owner: cfg.Owner,
		Repo:  cfg.Repo,
	}

	mintURL := cfg.MintURL
	if cfg.Forge == ForgeGitHub && mintURL == "" {
		return result, fmt.Errorf("internal error: mint URL not resolved for GitHub repo (public mode should default, private mode should fail validation)")
	}
	wifProvider := cfg.WIFProvider
	result.WIFProvider = wifProvider

	// When SkipScaffoldAndConfig is set, the caller handles scaffold delivery
	// and variable/secret writes externally (e.g., vendor mode commits
	// scaffold and vendor files together atomically via applyPerRepoScaffold).
	if cfg.SkipScaffoldAndConfig {
		result.Success = true
		progress(repoFullName, "done", "Pre-install steps complete")
		return result, nil
	}

	if cfg.InferenceProject != "" && !IsValidGCPProjectID(cfg.InferenceProject) {
		return result, fmt.Errorf("invalid GCP project ID %q", cfg.InferenceProject)
	}
	if cfg.InferenceRegion != "" && !IsValidGCPRegion(cfg.InferenceRegion) {
		return result, fmt.Errorf("invalid GCP region %q", cfg.InferenceRegion)
	}

	// Validate WIF provider when inference secrets will be written.
	if !cfg.ReuseSecrets && cfg.InferenceProject != "" {
		if wifProvider == "" {
			return result, fmt.Errorf("WIF provider required for repository secret configuration; set WIFProvider or enable WIF provisioning")
		}
		if !WIFProviderPattern.MatchString(wifProvider) {
			return result, fmt.Errorf("invalid WIF provider format %q: expected projects/{number}/locations/global/workloadIdentityPools/{pool}/providers/{id}", wifProvider)
		}
	}

	// Step 4: Generate scaffold files.
	progress(repoFullName, "scaffold", "Generating scaffold files")
	files, err := BuildScaffoldFiles(cfg)
	if err != nil {
		return result, fmt.Errorf("generating scaffold files: %w", err)
	}

	// Step 5: Write repository variables. Variables and secrets are
	// written before the scaffold commit so the workflow's required
	// secrets exist by the time an event triggers a run. This
	// eliminates the race window described in #6122.
	progress(repoFullName, "vars", "Configuring repository variables")
	repoVars, err := installVarsForForge(cfg, mintURL)
	if err != nil {
		return result, err
	}
	for _, name := range maputil.SortedKeys(repoVars) {
		if err := client.CreateOrUpdateRepoVariable(ctx, cfg.Owner, cfg.Repo, name, repoVars[name]); err != nil {
			return result, fmt.Errorf("setting repo variable %s: %w", name, err)
		}
	}
	progress(repoFullName, "vars", fmt.Sprintf("Set %d repository variables", len(repoVars)))

	// Step 6: Write repository secrets. Skipped when reusing existing secrets.
	repoSecrets := installSecretsForForge(cfg, wifProvider)
	if cfg.ReuseSecrets {
		progress(repoFullName, "secrets", "Reusing existing repository secrets")
	} else if len(repoSecrets) > 0 {
		progress(repoFullName, "secrets", "Configuring repository secrets")
		for _, name := range maputil.SortedKeys(repoSecrets) {
			if err := client.CreateRepoSecret(ctx, cfg.Owner, cfg.Repo, name, repoSecrets[name]); err != nil {
				return result, fmt.Errorf("setting repo secret %s: %w", name, err)
			}
		}
		progress(repoFullName, "secrets", fmt.Sprintf("Set %d repository secrets", len(repoSecrets)))
	}

	// Step 7: Commit scaffold files via the caller-provided commit function.
	// Moved after variable and secret writes to ensure the workflow's
	// required credentials exist before the workflow file goes live.
	progress(repoFullName, "scaffold", "Committing scaffold files")
	if commitErr := commitScaffold(ctx, cfg.Owner, cfg.Repo, files, cfg.Direct, false); commitErr != nil {
		return result, fmt.Errorf("committing scaffold: %w", commitErr)
	}
	progress(repoFullName, "scaffold", "Scaffold files committed")

	result.Success = true
	progress(repoFullName, "done", "Installation complete")
	return result, nil
}

// DriftConfig holds additional fields beyond ResolvedConfig that are
// needed to build a complete InstallConfig for drift detection. These
// fields come from the manifest or CLI flags and are not part of the
// per-repo resolved config.
type DriftConfig struct {
	// InferenceRegion is the GCP region for inference. Only available
	// from CLI flags on repos install; empty on the status path.
	InferenceRegion string

	// ReviewAppClientID is the OAuth client ID of the review agent's
	// GitHub App. Only available from CLI flags on repos install.
	ReviewAppClientID string

	// RunnerTags is a list of GitLab CI runner tags from the manifest's
	// GitLab platform section.
	RunnerTags []string
}

// driftInstallConfig constructs the InstallConfig used by both the
// status and converge paths for content drift checking. This is the
// single source of truth for input construction — callers may overlay
// converge-specific fields (resolved ref, PrebuiltScaffoldFiles) on
// the returned value but must not build InstallConfig from scratch.
func driftInstallConfig(resolved ResolvedConfig, dcfg DriftConfig) InstallConfig {
	ref := resolved.FullsendRef
	return InstallConfig{
		Owner:             resolved.Owner,
		Repo:              resolved.Repo,
		Forge:             resolved.Forge,
		Roles:             defaultRoles(nil),
		MintURL:           resolved.MintURL,
		UpstreamRef:       ref,
		UpstreamTag:       ref,
		Runtime:           resolved.Runtime,
		InferenceRegion:   dcfg.InferenceRegion,
		ReviewAppClientID: dcfg.ReviewAppClientID,
		RunnerTags:        dcfg.RunnerTags,
	}
}

// ExpectedScaffoldContent renders the scaffold files that a fresh install
// would produce for the given resolved config. The status path uses this
// to compare against installed files for content drift detection — when
// the rendered template differs from the installed file, the repo's
// scaffold is stale even if the ref string matches.
//
// When fullsend_ref pins a version that differs from the running binary,
// the refResolver fetches remote scaffold templates from the pinned ref
// so the baseline matches the pinned version, not the embedded templates.
// This mirrors the converge path's FetchRemoteScaffold logic. Both paths
// share driftInstallConfig as the underlying input builder and
// BuildScaffoldFiles as the renderer.
//
// Returns (nil, nil) when FullsendRef is empty — there is no expected
// ref to compare against.
func ExpectedScaffoldContent(ctx context.Context, resolved ResolvedConfig, dcfg DriftConfig, refResolver *RefResolver) ([]forge.TreeFile, error) {
	if resolved.FullsendRef == "" {
		return nil, nil
	}
	installCfg := driftInstallConfig(resolved, dcfg)

	// When the manifest pins a fullsend_ref, fetch remote scaffold
	// templates so the baseline matches the pinned version's templates
	// rather than the running binary's embedded templates. This is the
	// same logic the converge path uses in convergeContentDriftFiles.
	manifestRef := resolved.FullsendRef
	if manifestRef != "" && refResolver != nil {
		ref := manifestRef
		if isSemver(manifestRef) {
			if sha := refResolver.Resolve(ctx, manifestRef); sha != manifestRef {
				ref = sha
				installCfg.UpstreamRef = ref
			}
		}
		scaffoldFiles, fetchErr := FetchRemoteScaffold(
			ctx, refResolver.client,
			manifestRef, ref, resolved.Forge,
			dcfg.RunnerTags,
		)
		if fetchErr == nil {
			installCfg.PrebuiltScaffoldFiles = scaffoldFiles
		}
		// On fetch failure, fall back to embedded templates — same
		// best-effort semantics as the converge path.
	}

	return BuildScaffoldFiles(installCfg)
}

// BuildScaffoldFiles generates the scaffold tree files for a per-repo install.
// Exported so the CLI dry-run path can display the file list without running
// the full install.
func BuildScaffoldFiles(cfg InstallConfig) ([]forge.TreeFile, error) {
	var perRepoCfg config.PerRepoConfigWriter
	if cfg.PerRepoConfig != nil {
		perRepoCfg = cfg.PerRepoConfig
	} else {
		generated := config.NewPerRepoConfig(cfg.Roles, cfg.Owner+"/"+cfg.Repo)
		if cfg.Runtime != "" {
			generated.SetRuntime(cfg.Runtime)
		}
		perRepoCfg = generated
	}
	if err := perRepoCfg.Validate(); err != nil {
		return nil, fmt.Errorf("invalid config: %w", err)
	}
	cfgYAML, err := perRepoCfg.Marshal()
	if err != nil {
		return nil, fmt.Errorf("marshaling config: %w", err)
	}

	var installFiles scaffold.InstallFiles
	if cfg.PrebuiltScaffoldFiles != nil {
		installFiles = cfg.PrebuiltScaffoldFiles
	} else {
		switch cfg.Forge {
		case ForgeGitHub:
			installFiles, err = scaffold.CollectPerRepoInstallFiles(cfg.VendorBinary, cfg.UpstreamRef, cfg.UpstreamTag)
		case ForgeGitLab:
			installFiles, err = scaffold.CollectGitLabPerRepoInstallFiles(cfg.RunnerTags, cfg.UpstreamRef, cfg.UpstreamTag)
		default:
			return nil, fmt.Errorf("unsupported forge %q for scaffold generation", cfg.Forge)
		}
		if err != nil {
			return nil, fmt.Errorf("collecting install files: %w", err)
		}
	}

	var files []forge.TreeFile
	for _, f := range installFiles {
		files = append(files, forge.TreeFile{
			Path:    f.Path,
			Content: f.Content,
			Mode:    f.Mode,
		})
	}
	files = append(files, forge.TreeFile{
		Path:    ".fullsend/config.yaml",
		Content: cfgYAML,
		Mode:    "100644",
	})

	return files, nil
}

// ManagedVar describes a repository variable with its expected value and
// whether it is dynamic (mutated at runtime). Static variables are
// value-checked during drift detection; dynamic variables are
// presence-checked only.
type ManagedVar struct {
	Name    string
	Value   string
	Dynamic bool // true = presence-only (value mutated at runtime)
}

// managedVarsForForge returns the managed variables for a given forge,
// each annotated with whether the variable is dynamic. This is the
// single source of truth for variable classification — callers use the
// Dynamic flag to decide whether to compare values during drift
// detection, without maintaining a separate hardcoded list.
func managedVarsForForge(cfg InstallConfig, mintURL string) ([]ManagedVar, error) {
	switch cfg.Forge {
	case ForgeGitHub:
		vars := []ManagedVar{
			{Name: forge.PerRepoGuardVar, Value: "true"},
			{Name: "FULLSEND_MINT_URL", Value: mintURL},
		}
		if cfg.InferenceRegion != "" {
			vars = append(vars, ManagedVar{Name: "FULLSEND_GCP_REGION", Value: cfg.InferenceRegion})
		}
		if cfg.ReviewAppClientID != "" {
			vars = append(vars, ManagedVar{Name: "FULLSEND_REVIEW_CLIENT_ID", Value: cfg.ReviewAppClientID})
		}
		return vars, nil
	case ForgeGitLab:
		now := time.Now().UTC().Format(time.RFC3339)
		vars := []ManagedVar{
			{Name: forge.PerRepoGuardVar, Value: "true"},
			{Name: "FULLSEND_LAST_POLL_AT_FAST", Value: now, Dynamic: true},
			{Name: "FULLSEND_LAST_POLL_AT_FULL", Value: now, Dynamic: true},
			{Name: "FULLSEND_LABEL_STATE", Value: "{}", Dynamic: true},
		}
		if cfg.InferenceRegion != "" {
			vars = append(vars, ManagedVar{Name: "FULLSEND_GCP_REGION", Value: cfg.InferenceRegion})
		}
		return vars, nil
	default:
		return nil, fmt.Errorf("unsupported forge %q for variable configuration", cfg.Forge)
	}
}

// staticExpectedVarValues returns a map of variable names to expected
// values for all static (non-dynamic) managed variables. This is used
// by the converge and status discovery phases to pass expected values
// to ProbeComponents for value-level drift detection.
func staticExpectedVarValues(cfg InstallConfig, mintURL string) (map[string]string, error) {
	managed, err := managedVarsForForge(cfg, mintURL)
	if err != nil {
		return nil, err
	}
	vals := make(map[string]string)
	for _, v := range managed {
		if !v.Dynamic && v.Value != "" {
			vals[v.Name] = v.Value
		}
	}
	return vals, nil
}

func installVarsForForge(cfg InstallConfig, mintURL string) (map[string]string, error) {
	managed, err := managedVarsForForge(cfg, mintURL)
	if err != nil {
		return nil, err
	}
	vars := make(map[string]string, len(managed))
	for _, v := range managed {
		vars[v.Name] = v.Value
	}
	return vars, nil
}

// installSecretsForForge returns the inference secrets to write.
// Returns nil when InferenceProject is not set (the convergence
// layer validates that InferenceProject is provided for repos
// without existing secrets).
func installSecretsForForge(cfg InstallConfig, wifProvider string) map[string]string {
	if cfg.InferenceProject == "" {
		return nil
	}

	return map[string]string{
		"FULLSEND_GCP_PROJECT_ID":   cfg.InferenceProject,
		"FULLSEND_GCP_WIF_PROVIDER": wifProvider,
	}
}

// requiredVariables lists the per-repo variables that must exist for a
// complete installation. FULLSEND_GCP_REGION is excluded because it is
// conditionally set (only when --inference-region is provided) and may
// not be present when secrets are reused. Shared by install,
// checkInstallComponents, and uninstall.
var requiredVariables = []string{"FULLSEND_MINT_URL"}

// requiredSecrets lists the per-repo secrets that must exist for a
// complete installation. Shared by install, checkInstallComponents,
// and uninstall.
var requiredSecrets = []string{"FULLSEND_GCP_PROJECT_ID", "FULLSEND_GCP_WIF_PROVIDER"}

var gitlabRequiredVariables = []string{"FULLSEND_LAST_POLL_AT_FAST", "FULLSEND_LAST_POLL_AT_FULL", "FULLSEND_LABEL_STATE"}

func requiredVarsForForge(forgeName string) []string {
	if forgeName == ForgeGitLab {
		return gitlabRequiredVariables
	}
	return requiredVariables
}

func requiredSecretsForForge() []string {
	return requiredSecrets
}

// checkInstallComponents verifies that all per-repo installation
// components are present (and, when expectedVarValues is provided,
// that variable values match). Returns true only when every component
// matches.
func checkInstallComponents(ctx context.Context, client forge.Client, owner, repo, forgeName string, fc ForgeConfig, expectedVarValues map[string]string) (bool, error) {
	components, err := ProbeComponents(ctx, client, owner, repo, forgeName, fc, expectedVarValues)
	if err != nil {
		return false, err
	}
	return AllMatch(components), nil
}
