package repos

import (
	"bytes"
	"fmt"
	"net/url"
	"strings"

	"github.com/fullsend-ai/fullsend/internal/config"
	"github.com/fullsend-ai/fullsend/internal/urlutil"
	"gopkg.in/yaml.v3"
)

// managedConfigMarker is the ADR-0122 ownership marker every managed
// .fullsend/config.yaml write on the install path (desiredManagedConfig)
// prefixes to its canonical bytes, verbatim as specified in ADR-0122's
// "Decision" section. Its presence is what distinguishes a file this
// package owns from a hand-authored one: convergeManagedConfigFiles and
// checkManagedConfigDrift in overlay_lifecycle.go refuse to treat
// an existing markerless file as ordinary drift, since the manifest may
// not restate every restriction (kill_switch, roles,
// allowed_remote_resources, ...) the hand-authored file set, and silently
// overwriting it would drop them.
const managedConfigMarker = "# This file is managed by 'fullsend repos': repos-config-v1\n" +
	"# Do not edit this file directly; changes will be overwritten.\n"

// hasManagedConfigMarker reports whether content already begins with the
// ADR-0122 ownership marker written by desiredManagedConfig. A file
// lacking the marker predates managed-configuration adoption (or was
// edited by hand) and must not be silently rewritten as ordinary drift.
func hasManagedConfigMarker(content []byte) bool {
	return bytes.HasPrefix(content, []byte(managedConfigMarker))
}

// overlayManaged reports whether defaults.config or the repository config
// block opts this repository into a managed .fullsend/config.yaml overlay.
func overlayManaged(defaults, entry config.OverlayConfig) bool {
	return defaults.IsSet() || entry.IsSet()
}

// managedOverlay flattens defaults.config, the repository config, and
// authoritative runtime / allowed_remote_resources shorthands into a sparse
// overlay. It does not bake in code defaults or config.base.yaml.
func (m *Manifest) managedOverlay(entry RepoEntry) config.PerRepoConfigWriter {
	merged := config.MergeOverlays(m.Defaults.Config.Writer(), entry.Config.Writer())
	if merged == nil {
		merged = config.NewEmptyPerRepoOverlay()
	}
	config.ApplyOverlayShorthands(merged, resolveField(entry.Runtime, m.Defaults.Runtime, ""), overlayAllowlist(entry, m.Defaults))
	return merged
}

func overlayAllowlist(entry RepoEntry, defaults DefaultsConfig) []string {
	if entry.AllowedRemoteResources != nil {
		return entry.AllowedRemoteResources
	}
	return defaults.AllowedRemoteResources
}

// RenderManagedOverlay returns the canonical sparse configuration YAML body
// for a config-managed repository — the explicitly supplied manifest
// values, with no code defaults or config.base.yaml baked in. ok is false
// when the repository is not config-managed; data is then nil.
//
// The returned bytes deliberately carry no file header. perRepoConfig's
// Marshal() prepends perRepoConfigHeader, the unmanaged per-repo-install
// header — not the ADR 0122 ownership marker
// ("# This file is managed by 'fullsend repos': ...") that every managed
// .fullsend/config.yaml written by the install path begins with. This
// function has no adoption-detection state (no forge read of the existing
// file), so it cannot decide whether the marker belongs on the result or
// whether an existing file requires adoption first; it renders the config
// body only. desiredManagedConfig is the install-path renderer (#7632)
// that prefixes the marker and is compared against the installed file by
// convergeManagedConfigFiles / checkManagedConfigDrift in
// overlay_lifecycle.go, which also implement the adoption gate for
// an existing markerless file.
func (m *Manifest) RenderManagedOverlay(entry RepoEntry) (data []byte, ok bool, err error) {
	if !overlayManaged(m.Defaults.Config, entry.Config) {
		return nil, false, nil
	}
	body, err := marshalManagedConfig(m.managedOverlay(entry))
	if err != nil {
		return nil, true, err
	}
	return body, true, nil
}

// desiredManagedConfig returns the canonical managed-configuration bytes
// for a config-managed repository, prefixed with the ADR-0122 ownership
// marker (managedConfigMarker). ok is false when the repository is not
// config-managed. This is the install path's renderer: install, converge,
// and status all compare the installed .fullsend/config.yaml against these
// exact bytes, so the marker is part of both the write and the whole-file
// compare.
func desiredManagedConfig(resolved ResolvedConfig) (data []byte, ok bool, err error) {
	if !resolved.OverlayManaged {
		return nil, false, nil
	}
	body, err := marshalManagedConfig(resolved.Overlay)
	if err != nil {
		return nil, true, err
	}
	return append([]byte(managedConfigMarker), body...), true, nil
}

// marshalManagedConfig does not prefix its own errors with "managed
// config" — every caller already wraps the returned error with its own
// "rendering managed config..." context, and adding the same phrase here
// would stutter it.
func marshalManagedConfig(overlay config.PerRepoConfigWriter) ([]byte, error) {
	if overlay == nil {
		overlay = config.NewEmptyPerRepoOverlay()
	}
	if err := config.ValidateMergedOverlay(overlay); err != nil {
		return nil, err
	}
	if err := validateOverlayMintAndWIF(overlay); err != nil {
		return nil, err
	}
	if err := ValidateAllowedRemoteResourcesFormat("allowed_remote_resources", overlay.AllowedResources()); err != nil {
		return nil, err
	}
	body, err := yaml.Marshal(overlay)
	if err != nil {
		return nil, fmt.Errorf("marshaling: %w", err)
	}
	return body, nil
}

// LayeredConfig returns the effective per-repo configuration for entry:
// managed overlay → config.base.yaml (baseYAML) → code defaults.
// Unmanaged repositories skip the overlay layer. baseYAML may be empty.
func (m *Manifest) LayeredConfig(entry RepoEntry, baseYAML []byte) (config.PerRepoConfigReader, error) {
	var overlay config.PerRepoConfigWriter
	if overlayManaged(m.Defaults.Config, entry.Config) {
		overlay = m.managedOverlay(entry)
	}
	return config.LayerOnBase(overlay, baseYAML)
}

func validateManifestOverlays(m *Manifest) error {
	if err := validateOverlayBlock("defaults.config", m.Defaults.Config); err != nil {
		return err
	}
	for _, p := range []struct {
		name string
		cfg  *PlatformConfig
	}{{ForgeGitHub, m.GitHub}, {ForgeGitLab, m.GitLab}} {
		if p.cfg == nil {
			continue
		}
		for i, entry := range p.cfg.Repos {
			field := fmt.Sprintf("%s.repos[%d].config", p.name, i)
			if entry.Name != "" {
				field = fmt.Sprintf("%s.repos[%s].config", p.name, entry.Name)
			}
			if err := validateOverlayBlock(field, entry.Config); err != nil {
				return err
			}
			if !overlayManaged(m.Defaults.Config, entry.Config) {
				continue
			}
			overlay := m.managedOverlay(entry)
			if err := config.ValidateMergedOverlay(overlay); err != nil {
				return fmt.Errorf("%s: merged overlay: %w", field, err)
			}
			if err := validateOverlayMintAndWIF(overlay); err != nil {
				return fmt.Errorf("%s: merged overlay: %w", field, err)
			}
		}
	}
	return nil
}

// validateOverlayBlock validates a single overlay layer (defaults.config
// or one repository's raw config block) in isolation, before
// defaults.config and the repository config are merged and before
// repos.yaml shorthands are applied. It intentionally does not run the
// checks that need that merge (agent allowlist, override-only custom
// agents) — see config.ValidateOverlayLayer — those run again, correctly,
// against the merged overlay below.
func validateOverlayBlock(field string, o config.OverlayConfig) error {
	if !o.IsSet() {
		return nil
	}
	if err := config.ValidateOverlayLayer(o.Writer()); err != nil {
		return fmt.Errorf("%s: %w", field, err)
	}
	if err := validateOverlayMintAndWIF(o.Writer()); err != nil {
		return fmt.Errorf("%s: %w", field, err)
	}
	return nil
}

// validateOverlayMintAndWIF runs the same mint_url HTTPS/userinfo gate
// used for RepoEntry.MintURL and the CLI's validateMintURLHTTPS, plus the
// WIF provider resource-name pattern check, on an overlay layer or the
// shorthand-merged overlay. Neither field is touched by
// ApplyOverlayShorthands, so the same check is correct whether r is an
// isolated layer or the merged overlay; an unset value resolves through
// the parent chain to the code default (always a valid HTTPS mint URL),
// so this only ever flags a value the overlay itself set. Install and
// converge write these values into the managed `.fullsend/config.yaml`;
// this closes the format gate before that write.
// Unlike github.url/gitlab.url (validated via RejectExtraneousURLParts),
// mint_url is allowed to carry a path — e.g. a Cloud Functions mint
// endpoint — matching every other mint_url gate in this codebase.
func validateOverlayMintAndWIF(r config.PerRepoConfigReader) error {
	if mintURL := r.ConfigMintURL(); mintURL != "" {
		mu, err := url.Parse(mintURL)
		if err != nil || mu.Scheme != "https" || mu.Host == "" {
			return fmt.Errorf("mint_url must be a valid HTTPS URL, got %q", mintURL)
		}
		if mu.User != nil {
			return fmt.Errorf("mint_url must not contain userinfo, got %q", mintURL)
		}
	}
	if wif := r.ConfigInferenceWIFProvider(); wif != "" && !WIFProviderPattern.MatchString(wif) {
		return fmt.Errorf("inference.wif_provider %q does not match the required resource name pattern", wif)
	}
	return nil
}

// ValidateAllowedRemoteResourcesFormat checks that every entry in an
// allowed_remote_resources allowlist (repos.yaml defaults, a per-repo
// shorthand, or the shorthand once baked into a managed configuration
// file) is a well-formed prefix: a valid HTTPS URL, ending with "/", with no
// double-encoded sequences. These are the same format rules
// harness.ValidateAllowedRemoteResources applies at `fullsend run`/`lock`
// time; that check runs too late to guard this write path, since
// MatchingAllowedPrefixInList does a plain strings.HasPrefix match and a
// prefix missing its trailing slash can therefore match sibling
// hosts/paths it should not. It does not check coverage against an
// org-level allowlist — that requires the harness, which is not loaded
// here. Exported so repos.yaml write paths outside this package (the CLI's
// --allowed-remote-resources flag, `repos set-default`) can reject a
// malformed prefix before it is ever persisted, matching the check
// Manifest.Validate applies on load/converge.
func ValidateAllowedRemoteResourcesFormat(field string, list []string) error {
	for i, entry := range list {
		if !urlutil.IsURL(entry) {
			return fmt.Errorf("%s[%d]: %q is not a valid HTTPS URL", field, i, entry)
		}
		if !strings.HasSuffix(entry, "/") {
			return fmt.Errorf("%s[%d]: %q must end with /", field, i, entry)
		}
		if strings.Contains(strings.ToLower(entry), "%25") {
			return fmt.Errorf("%s[%d]: %q contains double-encoded sequence", field, i, entry)
		}
	}
	return nil
}
