// Package fetch provides an SSRF-hardened HTTP client for safely retrieving
// content from external URLs. It enforces HTTPS-only access, domain allowlists,
// DNS pre-resolution with IP validation, and DNS-rebinding protection via
// transport-level IP pinning.
package fetch

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"math"
	"math/rand/v2"
	"net"
	"net/http"
	"net/url"
	"strings"
	"syscall"
	"time"

	"github.com/fullsend-ai/fullsend/internal/netutil"
)

// FetchPolicy controls the security constraints applied when fetching a URL.
type FetchPolicy struct {
	// AllowedDomains is the list of permitted hostnames. Entries may use a
	// wildcard prefix (e.g. "*.example.com") to match any subdomain,
	// including multi-level subdomains (e.g. "deep.sub.example.com").
	AllowedDomains []string

	// AllowedPorts restricts which ports may be used. When empty, only
	// port 443 is permitted.
	AllowedPorts []string

	// MaxSizeBytes is the maximum response body size in bytes.
	MaxSizeBytes int64

	// Timeout is the overall HTTP request timeout.
	Timeout time.Duration

	// Offline, when true, causes FetchURL to reject all requests immediately.
	Offline bool

	// MaxRetries is the number of retry attempts for transient errors
	// (connection resets, timeouts, HTTP 429/502/503). Nil uses the
	// default of 3 retries. Zero disables retries.
	MaxRetries *int

	// RetryBackoff is the base duration for exponential backoff between
	// retries. Zero or negative uses the default of 500 ms. The actual
	// delay is jittered between 50–100% of the computed backoff to avoid
	// thundering-herd effects.
	RetryBackoff time.Duration

	// tlsConfig is an optional TLS configuration, used in tests to trust
	// the self-signed certificates generated by httptest.NewTLSServer.
	// Set via NewTestPolicy.
	tlsConfig *tls.Config

	// skipIPCheck disables the internal-IP validation step. This is used in
	// tests where the test server necessarily listens on 127.0.0.1.
	// Set via NewTestPolicy.
	skipIPCheck bool
}

const (
	// defaultMaxAttempts is the total number of request attempts
	// (1 initial + retries) when MaxRetries is nil. This matches the
	// codebase convention where the retry constant controls loop
	// iterations directly (e.g. github.go, gitlab.go, jira.go all
	// use `for attempt := range maxRetries`).
	defaultMaxAttempts = 4

	// defaultRetryBackoff is the base backoff duration used when
	// RetryBackoff is zero or negative.
	defaultRetryBackoff = 500 * time.Millisecond

	// maxBackoff caps the computed backoff to prevent overflow when
	// attempt counts are large.
	maxBackoff = 30 * time.Second
)

// NewTestPolicy returns a FetchPolicy configured for use with
// httptest.NewTLSServer. Testing only — do not use in production code.
// It enables the TLS config and skips internal-IP validation (necessary
// because test servers listen on 127.0.0.1). These overrides are
// unexported to prevent direct bypass of SSRF protections.
func NewTestPolicy(tlsConfig *tls.Config, allowedDomains, allowedPorts []string) FetchPolicy {
	return FetchPolicy{
		AllowedDomains: allowedDomains,
		AllowedPorts:   allowedPorts,
		MaxSizeBytes:   10 * 1024 * 1024,
		Timeout:        5 * time.Second,
		tlsConfig:      tlsConfig,
		skipIPCheck:    true,
	}
}

// DefaultPolicy is a sensible default policy allowing GitHub content hosts.
var DefaultPolicy = FetchPolicy{
	AllowedDomains: []string{"github.com", "raw.githubusercontent.com"},
	MaxSizeBytes:   10 * 1024 * 1024, // 10 MB
	Timeout:        30 * time.Second,
	// MaxRetries: nil → uses default (4 total attempts).
}

var (
	errOffline        = errors.New("fetch: offline mode enabled")
	errNotHTTPS       = errors.New("fetch: only https URLs are allowed")
	errDoubleEncoding = errors.New("fetch: URL contains double-encoded percent (%25)")
	errDomainBlocked  = errors.New("fetch: domain not in allowlist")
	errPortBlocked    = errors.New("fetch: port not allowed")
	errInternalIP     = errors.New("fetch: resolved IP is internal/reserved")
	errNoAddrs        = errors.New("fetch: DNS resolution returned no addresses")
	errNonOK          = errors.New("fetch: non-200 status code")
	errTooLarge       = errors.New("fetch: response body exceeds size limit")
)

// HTTPStatusError is returned when FetchURL gets a non-200 response.
type HTTPStatusError struct {
	Status int
}

func (e HTTPStatusError) Error() string {
	return fmt.Sprintf("%s: got %d", errNonOK.Error(), e.Status)
}

func (e HTTPStatusError) Unwrap() error { return errNonOK }

// FetchURL retrieves the content at rawURL subject to the given policy.
// It returns the response body bytes or an error describing why the fetch
// was rejected or failed.
func FetchURL(ctx context.Context, rawURL string, policy FetchPolicy) ([]byte, error) {
	// 1. Offline check.
	if policy.Offline {
		return nil, errOffline
	}

	// 2. Parse and validate scheme.
	parsed, err := url.Parse(rawURL)
	if err != nil {
		return nil, fmt.Errorf("fetch: invalid URL: %w", err)
	}
	if strings.ToLower(parsed.Scheme) != "https" {
		return nil, errNotHTTPS
	}

	// 3. Reject double-encoded percent signs.
	if strings.Contains(rawURL, "%25") {
		return nil, errDoubleEncoding
	}

	// 4. Domain allowlist.
	hostname := strings.ToLower(parsed.Hostname())
	if !isAllowedDomain(hostname, policy.AllowedDomains) {
		return nil, errDomainBlocked
	}

	// 5. DNS pre-resolution.
	addrs, err := net.DefaultResolver.LookupIPAddr(ctx, hostname)
	if err != nil {
		return nil, fmt.Errorf("fetch: DNS resolution failed for %s: %w", hostname, err)
	}
	if len(addrs) == 0 {
		return nil, errNoAddrs
	}

	// 6. Validate ALL resolved IPs.
	if !policy.skipIPCheck {
		for _, addr := range addrs {
			if netutil.IsInternal(addr.IP) {
				return nil, fmt.Errorf("%w: %s resolved to %s", errInternalIP, hostname, addr.IP)
			}
		}
	}

	// Determine the port (default 443 for HTTPS).
	port := parsed.Port()
	if port == "" {
		port = "443"
	}

	// 6b. Port restriction.
	allowedPorts := policy.AllowedPorts
	if len(allowedPorts) == 0 {
		allowedPorts = []string{"443"}
	}
	if !portAllowed(port, allowedPorts) {
		return nil, fmt.Errorf("%w: port %s", errPortBlocked, port)
	}

	// 7. Build transport with DNS-rebinding protection.
	//    Try each pre-validated IP in order for IPv4/IPv6 fallback.
	//    Each FetchURL call creates its own transport to pin resolved IPs;
	//    idle connections are closed after use.
	transport := &http.Transport{
		DialContext: func(dialCtx context.Context, _, _ string) (net.Conn, error) {
			d := net.Dialer{Timeout: policy.Timeout}
			var lastErr error
			for _, addr := range addrs {
				conn, err := d.DialContext(dialCtx, "tcp", net.JoinHostPort(addr.IP.String(), port))
				if err != nil {
					lastErr = err
					continue
				}
				return conn, nil
			}
			return nil, lastErr
		},
		TLSClientConfig: policy.tlsConfig,
	}
	defer transport.CloseIdleConnections()

	client := &http.Client{
		Transport: transport,
		Timeout:   policy.Timeout,
		// 8. Block redirects.
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, fmt.Errorf("fetch: failed to create request: %w", err)
	}

	// 9. Execute request with retry for transient errors.
	maxAttempts := defaultMaxAttempts
	if policy.MaxRetries != nil {
		maxAttempts = *policy.MaxRetries + 1
		if maxAttempts < 1 {
			maxAttempts = 1
		}
	}
	baseBackoff := policy.RetryBackoff
	if baseBackoff <= 0 {
		baseBackoff = defaultRetryBackoff
	}

	var lastErr error
	for attempt := range maxAttempts {
		if attempt > 0 {
			delay := retryBackoff(baseBackoff, attempt-1)
			select {
			case <-ctx.Done():
				return nil, fmt.Errorf("fetch: %w (after %d attempt(s), last error: %v)", ctx.Err(), attempt, lastErr)
			case <-time.After(delay):
			}
		}

		resp, doErr := client.Do(req)
		if doErr != nil {
			if isTransientRequestError(ctx, doErr) && attempt < maxAttempts-1 {
				lastErr = doErr
				continue
			}
			if lastErr != nil {
				return nil, fmt.Errorf("fetch: request failed: %w (after %d attempt(s), last transient error: %v)", doErr, attempt+1, lastErr)
			}
			return nil, fmt.Errorf("fetch: request failed: %w", doErr)
		}

		// Only accept 200 OK.
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			httpErr := HTTPStatusError{Status: resp.StatusCode}
			if isTransientStatusCode(resp.StatusCode) && attempt < maxAttempts-1 {
				lastErr = httpErr
				continue
			}
			if lastErr != nil {
				return nil, fmt.Errorf("%w (after %d attempt(s), last transient error: %v)", httpErr, attempt+1, lastErr)
			}
			return nil, httpErr
		}

		// 10. Size limit: read one extra byte to detect overflow.
		limited := io.LimitReader(resp.Body, policy.MaxSizeBytes+1)
		data, readErr := io.ReadAll(limited)
		resp.Body.Close()
		if readErr != nil {
			return nil, fmt.Errorf("fetch: reading response body: %w", readErr)
		}
		if int64(len(data)) > policy.MaxSizeBytes {
			return nil, errTooLarge
		}

		return data, nil
	}

	// Unreachable: the loop always returns. This satisfies the compiler.
	return nil, lastErr
}

// isAllowedDomain checks whether hostname matches any entry in the allowed
// list. Entries may be exact hostnames or wildcard patterns like "*.example.com"
// which match any subdomain of example.com (but not example.com itself).
func isAllowedDomain(hostname string, allowed []string) bool {
	for _, pattern := range allowed {
		pattern = strings.ToLower(pattern)
		if strings.HasPrefix(pattern, "*.") {
			// Wildcard: *.example.com matches sub.example.com
			// but not example.com itself.
			suffix := pattern[1:] // ".example.com"
			if strings.HasSuffix(hostname, suffix) && hostname != pattern[2:] {
				return true
			}
		} else if hostname == pattern {
			return true
		}
	}
	return false
}

func portAllowed(port string, allowed []string) bool {
	for _, p := range allowed {
		if port == p {
			return true
		}
	}
	return false
}

// isTransientRequestError reports whether a client.Do error is transient
// and worth retrying. Context cancellation and deadline errors are never
// transient — the caller chose to stop waiting.
//
// We check ctx.Err() rather than errors.Is(err, context.DeadlineExceeded)
// because http.Client.Timeout wraps context.DeadlineExceeded from an
// internal context even when the caller's context is still active. Such
// per-request timeouts on slow servers are transient and worth retrying.
func isTransientRequestError(ctx context.Context, err error) bool {
	if ctx.Err() != nil {
		return false
	}
	// HTTP client timeout (e.g. net/http.Client.Timeout exceeded) and
	// i/o timeouts — both surface via the Timeout() interface.
	var te interface{ Timeout() bool }
	if errors.As(err, &te) && te.Timeout() {
		return true
	}
	// Unexpected EOF / connection closure.
	if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
		return true
	}
	// Transient connection errors. Use typed syscall sentinels instead
	// of string matching — these are stable across platforms (Go maps
	// OS-specific codes to syscall.Errno on all supported targets).
	if errors.Is(err, syscall.ECONNRESET) || errors.Is(err, syscall.ECONNREFUSED) {
		return true
	}
	return false
}

// isTransientStatusCode reports whether an HTTP status code represents a
// transient server-side failure that may succeed on retry.
func isTransientStatusCode(code int) bool {
	return code == http.StatusTooManyRequests ||
		code == http.StatusBadGateway ||
		code == http.StatusServiceUnavailable
}

// retryBackoff calculates the delay before the next retry attempt using
// exponential backoff with jitter. The delay is jittered between 50–100%
// of the computed backoff to prevent thundering-herd effects. The result
// is capped at maxBackoff to prevent overflow at high attempt counts.
func retryBackoff(base time.Duration, attempt int) time.Duration {
	backoff := base * time.Duration(math.Pow(2, float64(attempt)))
	if backoff <= 0 || backoff > maxBackoff {
		backoff = maxBackoff
	}
	half := backoff / 2
	return half + time.Duration(rand.Int64N(int64(half)+1))
}

// ComputeSHA256 returns the lowercase hex-encoded SHA-256 digest of data.
func ComputeSHA256(data []byte) string {
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:])
}
