package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"strings"
	"testing"

	"github.com/fullsend-ai/fullsend/internal/forge"
	"github.com/fullsend-ai/fullsend/internal/preset"
	"github.com/fullsend-ai/fullsend/internal/repos"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// managedConfigMarker is the public ADR-0122 ownership marker written at
// the start of every managed .fullsend/config.yaml. Command-level tests
// assert this contract rather than importing the unexported constant.
const managedConfigMarker = "# This file is managed by 'fullsend repos': repos-config-v1\n" +
	"# Do not edit this file directly; changes will be overwritten.\n"

const githubManagedManifestYAML = `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
      config:
        kill_switch: true
`

const githubUnmanagedManifestYAML = `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
`

const githubMixedManifestYAML = `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/managed
      config:
        kill_switch: true
    - name: acme/unmanaged
`

const gitlabManagedManifestYAML = `version: 1
gitlab:
  url: https://gitlab.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: group/project
      config:
        kill_switch: true
`

func overlayPath(repo string) string {
	return repo + "/" + preset.OverlayPath
}

func githubManagedInstallOpts(manifestPath string, fc *forge.FakeClient) *reposInstallConfig {
	return &reposInstallConfig{
		manifest:               manifestPath,
		concurrency:            4,
		roles:                  []string{"triage"},
		direct:                 true,
		inferenceProject:       "inf-proj",
		inferenceProjectNumber: "123456789",
		inferenceRegion:        "us-central1",
		testClient:             fc,
	}
}

func statusJSON(t *testing.T, manifestPath string, fc *forge.FakeClient) (repos.StatusResult, string, error) {
	t.Helper()
	cmd := newReposStatusCmd()
	cmd.SetContext(context.Background())
	var buf bytes.Buffer
	cmd.SetOut(&buf)
	err := runReposStatus(cmd, manifestPath, true, nil, 4, fc)
	var result repos.StatusResult
	out := buf.String()
	if out != "" {
		require.NoError(t, json.Unmarshal([]byte(out), &result), "status JSON: %s", out)
	}
	return result, out, err
}

func overlayDrift(t *testing.T, result repos.StatusResult, repo string) (repos.Drift, bool) {
	t.Helper()
	for _, rs := range result.Repos {
		if rs.Owner+"/"+rs.Repo != repo {
			continue
		}
		for _, d := range rs.Drifts {
			if d.Field == preset.OverlayPath {
				return d, true
			}
		}
	}
	return repos.Drift{}, false
}

func TestRunRepos_ManagedConfigPublicContract(t *testing.T) {
	manifestPath := writeTestManifest(t, githubManagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))

	overlay := fc.FileContents[overlayPath("acme/api")]
	require.NotEmpty(t, overlay, "fresh managed install must write .fullsend/config.yaml")
	assert.True(t, bytes.HasPrefix(overlay, []byte(managedConfigMarker)), "ownership marker missing:\n%s", overlay)
	assert.Contains(t, string(overlay), "kill_switch: true")
	assert.NotContains(t, string(overlay), "roles:", "managed configuration must stay sparse")

	result, _, err := statusJSON(t, manifestPath, fc)
	if err != nil {
		assert.NotContains(t, err.Error(), "errored", "status errored after install: %v\n%s", err, mustEncode(t, result))
	}
	if d, found := overlayDrift(t, result, "acme/api"); found {
		t.Fatalf("status reported managed-configuration drift immediately after install: %+v", d)
	}

	drifted := []byte(managedConfigMarker + "kill_switch: false\n")
	fc.FileContents[overlayPath("acme/api")] = drifted

	result, _, err = statusJSON(t, manifestPath, fc)
	require.Error(t, err, "status must be non-zero when managed configuration drifted")
	d, found := overlayDrift(t, result, "acme/api")
	require.True(t, found, "status must report .fullsend/config.yaml drift, got %s", mustEncode(t, result))
	assert.Equal(t, "managed configuration", d.Expected)
	assert.Equal(t, "installed content differs", d.Actual)

	require.NoError(t, runReposInstall(context.Background(), &reposInstallConfig{
		manifest:    manifestPath,
		concurrency: 4,
		dryRun:      true,
		testClient:  fc,
	}))
	assert.Equal(t, drifted, fc.FileContents[overlayPath("acme/api")], "dry-run must not rewrite managed configuration")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))
	assert.Equal(t, overlay, fc.FileContents[overlayPath("acme/api")], "converge must restore the canonical managed file")

	result, _, err = statusJSON(t, manifestPath, fc)
	if err != nil {
		assert.NotContains(t, err.Error(), "errored")
	}
	if d, found := overlayDrift(t, result, "acme/api"); found {
		t.Fatalf("status still reports managed-configuration drift after converge: %+v", d)
	}
}

func TestRunReposInstall_ManagedConfigFreshInstallDryRun(t *testing.T) {
	manifestPath := writeTestManifest(t, githubManagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	opts := githubManagedInstallOpts(manifestPath, fc)
	opts.dryRun = true
	require.NoError(t, runReposInstall(context.Background(), opts))
	assert.Empty(t, fc.FileContents[overlayPath("acme/api")], "dry-run must not create managed configuration")
}

func TestRunReposInstall_UnmanagedLeavesInstallerOverlay(t *testing.T) {
	manifestPath := writeTestManifest(t, githubUnmanagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))

	overlay := fc.FileContents[overlayPath("acme/api")]
	require.NotEmpty(t, overlay, "unmanaged fresh install still writes the installer overlay")
	assert.False(t, bytes.HasPrefix(overlay, []byte(managedConfigMarker)), "unmanaged overlay must not carry the ownership marker:\n%s", overlay)
	assert.Contains(t, string(overlay), "roles:")
}

func TestRunReposInstall_ManagedConfigOnlyOneRepoManaged(t *testing.T) {
	manifestPath := writeTestManifest(t, githubMixedManifestYAML)
	fc := newInstallFakeClient("acme/managed", "acme/unmanaged")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))

	managed := fc.FileContents[overlayPath("acme/managed")]
	unmanaged := fc.FileContents[overlayPath("acme/unmanaged")]
	require.NotEmpty(t, managed)
	require.NotEmpty(t, unmanaged)
	assert.True(t, bytes.HasPrefix(managed, []byte(managedConfigMarker)))
	assert.Contains(t, string(managed), "kill_switch: true")
	assert.False(t, bytes.HasPrefix(unmanaged, []byte(managedConfigMarker)))
	assert.NotContains(t, string(unmanaged), "kill_switch:")
}

func TestRunReposInstall_ManagedConfigAdoptionRequired(t *testing.T) {
	manifestPath := writeTestManifest(t, githubManagedManifestYAML)
	fc := newInstalledFakeClientCLI("acme/api")
	original := []byte("kill_switch: false\n# hand-authored\n")
	fc.FileContents[overlayPath("acme/api")] = original

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))
	assert.Equal(t, original, fc.FileContents[overlayPath("acme/api")], "adoption-required install must leave the unmarked file untouched")

	result, _, err := statusJSON(t, manifestPath, fc)
	require.Error(t, err)
	d, found := overlayDrift(t, result, "acme/api")
	require.True(t, found, "status must report adoption required, got %s", mustEncode(t, result))
	assert.Equal(t, "managed configuration (adoption required)", d.Expected)
	assert.Contains(t, d.Actual, "ownership marker")
}

func TestRunReposStatus_UnmanagedDoesNotCompare(t *testing.T) {
	manifestPath := writeTestManifest(t, githubUnmanagedManifestYAML)
	fc := newInstalledFakeClientCLI("acme/api")
	fc.FileContents[overlayPath("acme/api")] = []byte("kill_switch: true\n# local\n")

	result, _, _ := statusJSON(t, manifestPath, fc)
	if d, found := overlayDrift(t, result, "acme/api"); found {
		t.Fatalf("unmanaged configuration must not be compared, got %+v", d)
	}
}

func TestRunReposInstall_ForbiddenShorthandInConfig(t *testing.T) {
	tests := []struct {
		name    string
		yaml    string
		wantErr string
	}{
		{
			name: "runtime inside defaults.config",
			yaml: `version: 1
defaults:
  config:
    runtime: pi
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
`,
			wantErr: "runtime is not allowed inside config",
		},
		{
			name: "allowed_remote_resources inside repo config",
			yaml: `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
      config:
        allowed_remote_resources: []
`,
			wantErr: "allowed_remote_resources is not allowed inside config",
		},
		{
			name: "unknown field",
			yaml: `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
      config:
        bogus: true
`,
			wantErr: `unknown field "bogus"`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			manifestPath := writeTestManifest(t, tt.yaml)
			fc := newInstallFakeClient("acme/api")
			err := runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc))
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.wantErr)

			_, _, statusErr := statusJSON(t, manifestPath, fc)
			require.Error(t, statusErr)
			assert.Contains(t, statusErr.Error(), tt.wantErr)
		})
	}
}

func TestRunRepos_GitLabManagedConfigStatusAndDryRun(t *testing.T) {
	manifestPath := writeTestManifest(t, gitlabManagedManifestYAML)
	fc := newGitLabInstalledFake("group/project")
	drifted := []byte(managedConfigMarker + "kill_switch: false\n")
	fc.FileContents[overlayPath("group/project")] = drifted

	result, _, err := statusJSON(t, manifestPath, fc)
	require.Error(t, err)
	d, found := overlayDrift(t, result, "group/project")
	require.True(t, found, "GitLab status must report managed-configuration drift, got %s", mustEncode(t, result))
	assert.Equal(t, "managed configuration", d.Expected)

	require.NoError(t, runReposInstall(context.Background(), &reposInstallConfig{
		manifest:    manifestPath,
		concurrency: 4,
		dryRun:      true,
		testClient:  fc,
	}))
	assert.Equal(t, drifted, fc.FileContents[overlayPath("group/project")], "GitLab dry-run must not rewrite managed configuration")
}

func newGitLabInstalledFake(repo string) *forge.FakeClient {
	fc := forge.NewFakeClient()
	fc.InstallationToken = true
	fc.AuthenticatedUser = "fullsend-app[bot]"
	fc.CollaboratorPermissions = map[string]string{
		repo + "/fullsend-app[bot]": "write",
	}
	parts := strings.SplitN(repo, "/", 2)
	fc.Repos = []forge.Repository{{
		FullName:      repo,
		Name:          parts[1],
		DefaultBranch: "main",
	}}
	fc.Secrets[repo+"/"+forge.SecretForgeToken] = true
	fc.Secrets[repo+"/"+forge.SecretGCPProjectID] = true
	fc.Secrets[repo+"/"+forge.SecretGCPWIFProvider] = true
	fc.PipelineSchedules[repo] = []forge.PipelineSchedule{
		{Description: "fullsend slash poll", Active: true},
		{Description: "fullsend event poll", Active: true},
	}
	fc.FileContents[repo+"/.gitlab/ci/fullsend-pipeline.yml"] = []byte("---\n# fullsend-ref: v1.0.0\n  ref: v1.0.0\n")
	return fc
}

func mustEncode(t *testing.T, v any) string {
	t.Helper()
	b, err := json.Marshal(v)
	require.NoError(t, err)
	return string(b)
}
