package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/fullsend-ai/fullsend/internal/forge"
	"github.com/fullsend-ai/fullsend/internal/preset"
	"github.com/fullsend-ai/fullsend/internal/repos"
	"github.com/fullsend-ai/fullsend/internal/scaffold"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// managedConfigMarker is the public ADR-0122 ownership marker written at
// the start of every managed .fullsend/config.yaml. Command-level tests
// assert this contract rather than importing the unexported constant.
const managedConfigMarker = "# This file is managed by 'fullsend repos': repos-config-v1\n" +
	"# Do not edit this file directly; changes will be overwritten.\n"

const githubManagedManifestYAML = `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  inference:
    auth: vertex-wif
  repos:
    - name: acme/api
      config:
        kill_switch: true
`

const githubUnmanagedManifestYAML = `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  inference:
    auth: vertex-wif
  repos:
    - name: acme/api
`

const githubMixedManifestYAML = `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  inference:
    auth: vertex-wif
  repos:
    - name: acme/managed
      config:
        kill_switch: true
    - name: acme/unmanaged
`

const gitlabManagedManifestYAML = `version: 1
gitlab:
  url: https://gitlab.example.com
  fullsend_ref: v1.0.0
  inference:
    auth: openai-api-key
  repos:
    - name: group/project
      config:
        kill_switch: true
`

func overlayPath(repo string) string {
	return repo + "/" + preset.OverlayPath
}

func githubManagedInstallOpts(manifestPath string, fc *forge.FakeClient) *reposInstallConfig {
	return &reposInstallConfig{
		manifest:               manifestPath,
		concurrency:            4,
		roles:                  []string{"triage"},
		direct:                 true,
		inferenceProject:       "inf-proj",
		inferenceProjectNumber: "123456789",
		inferenceRegion:        "us-central1",
		testClient:             fc,
	}
}

// useOpenAIInputs swaps the helper's default Vertex inputs for an OpenAI
// key; Converge rejects input groups that no selected repository consumes.
//
// Converge fails closed when it cannot fetch an explicit pin's scaffold to
// verify the OpenAI credential contract, so the fake upstream also serves a
// shim at the v1.0.0 and v2.0.0 pins these tests use that forwards the key.
func useOpenAIInputs(opts *reposInstallConfig) *reposInstallConfig {
	if fc, ok := opts.testClient.(*forge.FakeClient); ok {
		shim, err := scaffold.PerRepoShimTemplate()
		if err != nil {
			panic(err)
		}
		for _, ref := range []string{"v1.0.0", "v2.0.0"} {
			fc.FileContentsRef["fullsend-ai/fullsend/internal/scaffold/fullsend-repo/templates/shim-per-repo.yaml@"+ref] = shim
		}
	}
	opts.inferenceProject = ""
	opts.inferenceProjectNumber = ""
	opts.inferenceRegion = ""
	opts.openAIAPIKey = "test-openai-key"
	return opts
}

func statusJSON(t *testing.T, manifestPath string, fc forge.Client) (repos.StatusResult, error) {
	t.Helper()
	cmd := newReposStatusCmd()
	cmd.SetContext(context.Background())
	var buf bytes.Buffer
	cmd.SetOut(&buf)
	err := runReposStatus(cmd, &reposStatusConfig{
		manifest:    manifestPath,
		jsonOutput:  true,
		concurrency: 4,
		testClient:  fc,
	})
	var result repos.StatusResult
	out := buf.String()
	if out != "" {
		require.NoError(t, json.Unmarshal([]byte(out), &result), "status JSON: %s", out)
	}
	return result, err
}

func overlayDrift(t *testing.T, result repos.StatusResult, repo string) (repos.Drift, bool) {
	t.Helper()
	for _, rs := range result.Repos {
		if rs.Owner+"/"+rs.Repo != repo {
			continue
		}
		for _, d := range rs.Drifts {
			if d.Field == preset.OverlayPath {
				return d, true
			}
		}
	}
	return repos.Drift{}, false
}

func TestRunRepos_ManagedConfigPublicContract(t *testing.T) {
	manifestPath := writeTestManifest(t, githubManagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))

	overlay := fc.FileContents[overlayPath("acme/api")]
	require.NotEmpty(t, overlay, "fresh managed install must write .fullsend/config.yaml")
	assert.True(t, bytes.HasPrefix(overlay, []byte(managedConfigMarker)), "ownership marker missing:\n%s", overlay)
	assert.Contains(t, string(overlay), "kill_switch: true")
	assert.NotContains(t, string(overlay), "roles:", "managed configuration must stay sparse")

	result, err := statusJSON(t, manifestPath, fc)
	require.NoError(t, err)
	if d, found := overlayDrift(t, result, "acme/api"); found {
		t.Fatalf("status reported managed-configuration drift immediately after install: %+v", d)
	}

	drifted := []byte(managedConfigMarker + "kill_switch: false\n")
	fc.FileContents[overlayPath("acme/api")] = drifted

	result, err = statusJSON(t, manifestPath, fc)
	require.Error(t, err, "status must be non-zero when managed configuration drifted")
	d, found := overlayDrift(t, result, "acme/api")
	require.True(t, found, "status must report .fullsend/config.yaml drift, got %s", mustEncode(t, result))
	assert.Equal(t, "managed configuration", d.Expected)
	assert.Equal(t, "installed content differs", d.Actual)

	require.NoError(t, runReposInstall(context.Background(), &reposInstallConfig{
		manifest:    manifestPath,
		concurrency: 4,
		dryRun:      true,
		testClient:  fc,
	}))
	assert.Equal(t, drifted, fc.FileContents[overlayPath("acme/api")], "dry-run must not rewrite managed configuration")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))
	assert.Equal(t, overlay, fc.FileContents[overlayPath("acme/api")], "converge must restore the canonical managed file")

	result, err = statusJSON(t, manifestPath, fc)
	require.NoError(t, err)
	if d, found := overlayDrift(t, result, "acme/api"); found {
		t.Fatalf("status still reports managed-configuration drift after converge: %+v", d)
	}
}

func TestRunReposInstall_ManagedConfigFreshInstallDryRun(t *testing.T) {
	manifestPath := writeTestManifest(t, githubManagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	opts := githubManagedInstallOpts(manifestPath, fc)
	opts.dryRun = true
	require.NoError(t, runReposInstall(context.Background(), opts))
	assert.Empty(t, fc.FileContents[overlayPath("acme/api")], "dry-run must not create managed configuration")
}

// A repository with no config key is still managed: the first install
// persists the upstream create_issues default in its manifest entry and
// renders exactly that into the marked sparse overlay (#8218).
func TestRunReposInstall_NoConfigKeyWritesSparseManagedOverlay(t *testing.T) {
	manifestPath := writeTestManifest(t, githubUnmanagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))

	overlay := fc.FileContents[overlayPath("acme/api")]
	assert.Equal(t, managedConfigMarker+"create_issues:\n    allow_targets:\n        repos:\n            - fullsend-ai/fullsend\n", string(overlay))

	reloaded, err := repos.LoadManifest(context.Background(), manifestPath)
	require.NoError(t, err)
	require.True(t, reloaded.GitHub.Repos[0].Config.IsSet(), "the default must be persisted on the entry")
	body, ok, err := reloaded.RenderManagedConfig(reloaded.GitHub.Repos[0])
	require.NoError(t, err)
	require.True(t, ok)
	assert.Equal(t, string(overlay), managedConfigMarker+string(body), "manifest and overlay must agree")
}

func TestRunReposInstall_NoConfigKeyDryRunWritesNothing(t *testing.T) {
	manifestPath := writeTestManifest(t, githubUnmanagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	opts := githubManagedInstallOpts(manifestPath, fc)
	opts.dryRun = true
	require.NoError(t, runReposInstall(context.Background(), opts))

	assert.Empty(t, fc.FileContents[overlayPath("acme/api")])
	data, err := os.ReadFile(manifestPath)
	require.NoError(t, err)
	assert.Equal(t, githubUnmanagedManifestYAML, string(data), "dry-run must not rewrite the manifest")
}

func TestRunReposInstall_ExplicitRolesPersistedInManifest(t *testing.T) {
	manifestPath := writeTestManifest(t, githubUnmanagedManifestYAML)
	fc := newInstallFakeClient("acme/api")

	opts := githubManagedInstallOpts(manifestPath, fc)
	opts.roles = []string{"triage", "review"}
	opts.rolesChanged = true
	require.NoError(t, runReposInstall(context.Background(), opts))

	reloaded, err := repos.LoadManifest(context.Background(), manifestPath)
	require.NoError(t, err)
	resolved, ok := reloaded.ResolveConfig("acme", "api")
	require.True(t, ok)
	assert.Equal(t, []string{"triage", "review"}, resolved.Managed.ConfigRoles())
	overlay := string(fc.FileContents[overlayPath("acme/api")])
	assert.Contains(t, overlay, "roles:")
	assert.Contains(t, overlay, "- review")
	assert.Contains(t, overlay, "fullsend-ai/fullsend")
}

func TestRunReposInstall_ExplicitCreateIssuesIsNotOverridden(t *testing.T) {
	manifest := strings.Replace(githubUnmanagedManifestYAML, "    - name: acme/api\n",
		"    - name: acme/api\n      config:\n        create_issues:\n          allow_targets:\n            repos:\n              - acme/other\n", 1)
	manifestPath := writeTestManifest(t, manifest)
	fc := newInstallFakeClient("acme/api")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))

	overlay := string(fc.FileContents[overlayPath("acme/api")])
	assert.Contains(t, overlay, "acme/other")
	assert.NotContains(t, overlay, "fullsend-ai/fullsend")
}

func TestRunReposInstall_ReadOnlyManifestFailsWithSuggestedEdit(t *testing.T) {
	// An HTTPS manifest cannot be written back: the install fails before
	// any forge write and prints the exact per-repo config edit.
	m, loadErr := repos.LoadManifest(context.Background(), writeTestManifest(t, githubUnmanagedManifestYAML))
	require.NoError(t, loadErr)
	_, err := repos.EnsureManagedConfigDefaults(context.Background(), repos.ManagedConfigWritebackConfig{
		Manifest: m, ManifestPath: "https://example.invalid/repos.yaml",
	}, newSingleClientFactory(newInstallFakeClient("acme/api")), nil)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "read-only")
	assert.Contains(t, err.Error(), `entry "acme/api"`)
	assert.Contains(t, err.Error(), "create_issues:")
	assert.Contains(t, err.Error(), "- fullsend-ai/fullsend")
}

func TestRunReposInstall_ManagedConfigBothReposManaged(t *testing.T) {
	manifestPath := writeTestManifest(t, githubMixedManifestYAML)
	fc := newInstallFakeClient("acme/managed", "acme/unmanaged")

	require.NoError(t, runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc)))

	managed := fc.FileContents[overlayPath("acme/managed")]
	plain := fc.FileContents[overlayPath("acme/unmanaged")]
	require.NotEmpty(t, managed)
	require.NotEmpty(t, plain)
	assert.True(t, bytes.HasPrefix(managed, []byte(managedConfigMarker)))
	assert.Contains(t, string(managed), "kill_switch: true")
	assert.True(t, bytes.HasPrefix(plain, []byte(managedConfigMarker)), "a repo without a config key is managed too")
	assert.NotContains(t, string(plain), "kill_switch:")
}

// A markerless overlay is an adoption case even without a config key: the
// install fails before any manifest or forge write and leaves it alone.
func TestRunReposInstall_MarkerlessOverlayBlocksInstall(t *testing.T) {
	for name, manifestYAML := range map[string]string{
		"with config key":    githubManagedManifestYAML,
		"without config key": githubUnmanagedManifestYAML,
	} {
		t.Run(name, func(t *testing.T) {
			manifestPath := writeTestManifest(t, manifestYAML)
			fc := newInstalledFakeClientCLI("acme/api")
			original := []byte("kill_switch: false\n# hand-authored\n")
			fc.FileContents[overlayPath("acme/api")] = original

			err := runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc))
			require.Error(t, err)
			assert.Contains(t, err.Error(), "adoption required")
			assert.Equal(t, original, fc.FileContents[overlayPath("acme/api")], "the unmarked file must be untouched")
			data, readErr := os.ReadFile(manifestPath)
			require.NoError(t, readErr)
			assert.Equal(t, manifestYAML, string(data), "no manifest write before the preflight passes")

			result, statusErr := statusJSON(t, manifestPath, fc)
			require.Error(t, statusErr)
			d, found := overlayDrift(t, result, "acme/api")
			require.True(t, found, "status must report adoption required, got %s", mustEncode(t, result))
			assert.Equal(t, "managed configuration (adoption required)", d.Expected)
			assert.Contains(t, d.Actual, "ownership marker")
		})
	}
}

func TestRunReposStatus_NoConfigKeyMarkerlessOverlayRequiresAdoption(t *testing.T) {
	manifestPath := writeTestManifest(t, githubUnmanagedManifestYAML)
	fc := newInstalledFakeClientCLI("acme/api")
	fc.FileContents[overlayPath("acme/api")] = []byte("keep_history: true\n# local\n")

	result, _ := statusJSON(t, manifestPath, fc)
	d, found := overlayDrift(t, result, "acme/api")
	require.True(t, found, "a markerless overlay needs adoption even without a config key")
	assert.Contains(t, d.Expected, "adoption required")
}

func TestRunReposInstall_ForbiddenShorthandInConfig(t *testing.T) {
	tests := []struct {
		name    string
		yaml    string
		wantErr string
	}{
		{
			name: "runtime inside defaults.config",
			yaml: `version: 1
defaults:
  config:
    runtime: pi
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
`,
			wantErr: "runtime is not allowed inside config",
		},
		{
			name: "allowed_remote_resources inside repo config",
			yaml: `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
      config:
        allowed_remote_resources: []
`,
			wantErr: "allowed_remote_resources is not allowed inside config",
		},
		{
			name: "unknown field",
			yaml: `version: 1
github:
  mint_url: https://mint.example.com
  fullsend_ref: v1.0.0
  repos:
    - name: acme/api
      config:
        bogus: true
`,
			wantErr: `unknown field "bogus"`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			manifestPath := writeTestManifest(t, tt.yaml)
			fc := newInstallFakeClient("acme/api")
			err := runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, fc))
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.wantErr)

			_, statusErr := statusJSON(t, manifestPath, fc)
			require.Error(t, statusErr)
			assert.Contains(t, statusErr.Error(), tt.wantErr)
		})
	}
}

func TestRunRepos_GitLabManagedConfigStatusAndDryRun(t *testing.T) {
	manifestPath := writeTestManifest(t, gitlabManagedManifestYAML)
	fc := newGitLabInstalledFake("group/project")
	drifted := []byte(managedConfigMarker + "kill_switch: false\n")
	fc.FileContents[overlayPath("group/project")] = drifted

	result, err := statusJSON(t, manifestPath, fc)
	require.Error(t, err)
	d, found := overlayDrift(t, result, "group/project")
	require.True(t, found, "GitLab status must report managed-configuration drift, got %s", mustEncode(t, result))
	assert.Equal(t, "managed configuration", d.Expected)

	require.NoError(t, runReposInstall(context.Background(), &reposInstallConfig{
		manifest:    manifestPath,
		concurrency: 4,
		dryRun:      true,
		testClient:  fc,
	}))
	assert.Equal(t, drifted, fc.FileContents[overlayPath("group/project")], "GitLab dry-run must not rewrite managed configuration")
}

func newGitLabInstalledFake(repo string) *forge.FakeClient {
	fc := forge.NewFakeClient()
	seedGitLabInputPrerequisites(fc, repo, "v1.0.0")
	fc.InstallationToken = true
	fc.AuthenticatedUser = "fullsend-app[bot]"
	fc.CollaboratorPermissions = map[string]string{
		repo + "/fullsend-app[bot]": "write",
	}
	parts := strings.SplitN(repo, "/", 2)
	fc.Repos = []forge.Repository{{
		FullName:      repo,
		Name:          parts[1],
		DefaultBranch: "main",
	}}
	fc.Secrets[repo+"/"+forge.SecretForgeToken] = true
	fc.Secrets[repo+"/"+forge.SecretOpenAIAPIKey] = true
	fc.PipelineSchedules[repo] = []forge.PipelineSchedule{
		{ID: 1, Description: "fullsend slash poll", Active: true},
		{ID: 2, Description: "fullsend event poll", Active: true},
	}
	fc.FileContents[repo+"/.gitlab/ci/fullsend-pipeline.yml"] = []byte("---\n# fullsend-ref: v1.0.0\n  ref: v1.0.0\n")
	return fc
}

func mustEncode(t *testing.T, v any) string {
	t.Helper()
	b, err := json.Marshal(v)
	require.NoError(t, err)
	return string(b)
}

// A zero-byte overlay is an existing markerless file: install stops before
// any write, and status reports how to adopt it, with no Fullsend
// components present.
func TestRunRepos_ZeroByteOverlayRequiresAdoption(t *testing.T) {
	manifestPath := writeTestManifest(t, githubUnmanagedManifestYAML)
	fc := forge.NewFakeClient()
	fc.FileContents[overlayPath("acme/api")] = []byte{}

	err := runReposInstall(context.Background(), githubManagedInstallOpts(manifestPath, newInstallFakeClientWithOverlay(t, "acme/api", []byte{})))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "adoption required")

	result, _ := statusJSON(t, manifestPath, fc)
	d, found := overlayDrift(t, result, "acme/api")
	require.True(t, found, "status must report the zero-byte overlay, got %s", mustEncode(t, result))
	assert.Contains(t, d.Expected, "adoption required")
	assert.Contains(t, d.Detail, "proposed repos.yaml entry for acme/api")
}

func TestRunReposStatus_AdoptionDetailInJSONAndTable(t *testing.T) {
	manifestPath := writeTestManifest(t, githubManagedManifestYAML)
	fc := forge.NewFakeClient()
	fc.FileContents[overlayPath("acme/api")] = []byte("kill_switch: false\nruntime: pi\n")

	result, _ := statusJSON(t, manifestPath, fc)
	d, found := overlayDrift(t, result, "acme/api")
	require.True(t, found)
	for _, want := range []string{"proposed repos.yaml entry", "runtime: pi", "- kill_switch: false", "+ kill_switch: true"} {
		assert.Contains(t, d.Detail, want)
	}

	var buf bytes.Buffer
	cmd := newReposStatusCmd()
	cmd.SetOut(&buf)
	printStatusTable(cmd, &result)
	out := buf.String()
	assert.Contains(t, out, "acme/api "+preset.OverlayPath+":")
	assert.Contains(t, out, "  proposed repos.yaml entry for acme/api")
	assert.Contains(t, out, "+ kill_switch: true")
}

func newInstallFakeClientWithOverlay(t *testing.T, repo string, overlay []byte) *forge.FakeClient {
	t.Helper()
	fc := newInstallFakeClient(repo)
	fc.FileContents[overlayPath(repo)] = overlay
	return fc
}
