receivers:
  otlpjsonfile:
    include:
      - "${env:REPLAY_INCLUDE}"
    start_at: beginning

exporters:
  otlphttp:
    endpoint: "${env:REPLAY_ENDPOINT}"

service:
  pipelines:
    traces:
      receivers: [otlpjsonfile]
      exporters: [otlphttp]
