import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  cli: [
    {
      type: 'doc',
      id: 'cli/README',
      label: 'Overview',
    },
    'cli/github',
    'cli/inference',
    'cli/mint',
  ],
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: {type: 'doc', id: 'guides/getting-started/README'},
      items: [
        'guides/getting-started/getting-inference',
        'guides/getting-started/configuring-github',
        'guides/getting-started/org-mode',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      link: {type: 'doc', id: 'agents/README'},
      items: [
        'agents/triage',
        'agents/code',
        'agents/review',
        'agents/fix',
        'agents/retro',
        'agents/prioritize',
      ],
    },
    {
      type: 'category',
      label: 'User Guides',
      link: {type: 'doc', id: 'guides/README'},
      items: [
        'guides/user/bugfix-workflow',
        'guides/user/customizing-agents',
        'guides/user/customizing-with-agents-md',
        'guides/user/customizing-with-skills',
        'guides/user/building-custom-agents',
        'guides/user/running-agents-locally',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'vision',
        'architecture',
        'runtimes',
        'glossary',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/README'},
      items: [
        'reference/installation',
        'reference/github-setup',
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [
        'guides/infrastructure/infrastructure-reference',
        'guides/infrastructure/mint-administration',
        'guides/infrastructure/private-repositories',
        'guides/infrastructure/distributed-tracing',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Development',
          items: [
            'guides/dev/cli-internals',
            'guides/dev/e2e-testing',
            'guides/dev/testing-workflows',
          ],
        },
        'roadmap',
        'landscape',
        'site-deployment',
        {
          type: 'category',
          label: 'Architecture Decisions',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'ADRs'},
          ],
        },
        {
          type: 'category',
          label: 'Design Documents',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'problems'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Internals',
      collapsed: true,
      items: [
        'admin-oauth-worker',
        {
          type: 'category',
          label: 'Specifications',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'superpowers/specs'},
          ],
        },
        {
          type: 'category',
          label: 'Implementation Plans',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'superpowers/plans'},
            {type: 'autogenerated', dirName: 'plans'},
          ],
        },
        {
          type: 'category',
          label: 'Experiments',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'superpowers/experiments'},
          ],
        },
      ],
    },
  ],
};

export default sidebars;
