package lock

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var testTime = time.Date(2026, 6, 8, 12, 0, 0, 0, time.UTC)

func TestLoad_ValidLockFile(t *testing.T) {
	content := `version: 1
generated_at: 2026-06-08T12:00:00Z
harnesses:
  code:
    source: harness/code.yaml
    sha256: abc123def456abc123def456abc123def456abc123def456abc123def456abcd
    resolved_at: 2026-06-08T12:00:00Z
    dependencies:
      - field: agent
        url: https://github.com/fullsend-ai/library/agents/code.md
        sha256: def456abc123def456abc123def456abc123def456abc123def456abc123defg
        fetched_at: 2026-06-08T11:59:55Z
`
	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	lf, err := Load(path)
	require.NoError(t, err)
	require.NotNil(t, lf)

	assert.Equal(t, 1, lf.Version)
	assert.Equal(t, testTime, lf.GeneratedAt)

	hl := lf.Lookup("code")
	require.NotNil(t, hl)
	assert.Equal(t, "harness/code.yaml", hl.Source)
	require.Len(t, hl.Dependencies, 1)
	assert.Equal(t, "agent", hl.Dependencies[0].Field)
	assert.Equal(t, "https://github.com/fullsend-ai/library/agents/code.md", hl.Dependencies[0].URL)
}

func TestLoad_FileNotFound(t *testing.T) {
	lf, err := Load(filepath.Join(t.TempDir(), "nonexistent.yaml"))
	require.NoError(t, err)
	assert.Nil(t, lf)
}

func TestLoad_MalformedYAML(t *testing.T) {
	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, os.WriteFile(path, []byte("{{not yaml"), 0o644))

	_, err := Load(path)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "parsing lock file")
}

func TestLoad_UnsupportedVersion(t *testing.T) {
	content := `version: 99
generated_at: 2026-06-08T12:00:00Z
harnesses: {}
`
	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	_, err := Load(path)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unsupported lock file version 99")
}

func TestSave_RoundTrip(t *testing.T) {
	lf := &LockFile{
		Version:     1,
		GeneratedAt: testTime,
		Harnesses: map[string]HarnessLock{
			"code": {
				Source:     "harness/code.yaml",
				SHA256:     "abc123",
				ResolvedAt: testTime,
				Dependencies: []DependencyEntry{
					{
						Field:     "agent",
						URL:       "https://example.com/agents/code.md",
						SHA256:    "def456",
						FetchedAt: testTime,
					},
					{
						Field:     "skills[0]",
						URL:       "https://example.com/skills/rust/SKILL.md",
						SHA256:    "ghi789",
						FetchedAt: testTime,
						TransitiveDeps: []DependencyEntry{
							{
								Field:     "skills[dep0]",
								URL:       "https://example.com/skills/common/SKILL.md",
								SHA256:    "jkl012",
								FetchedAt: testTime,
							},
						},
					},
				},
			},
		},
	}

	path := filepath.Join(t.TempDir(), ".fullsend", "lock.yaml")
	require.NoError(t, Save(path, lf))

	loaded, err := Load(path)
	require.NoError(t, err)
	require.NotNil(t, loaded)

	assert.Equal(t, 1, loaded.Version)
	assert.Equal(t, testTime, loaded.GeneratedAt)

	hl := loaded.Lookup("code")
	require.NotNil(t, hl)
	assert.Equal(t, "harness/code.yaml", hl.Source)
	assert.Equal(t, "abc123", hl.SHA256)
	require.Len(t, hl.Dependencies, 2)

	assert.Equal(t, "agent", hl.Dependencies[0].Field)
	assert.Equal(t, "https://example.com/agents/code.md", hl.Dependencies[0].URL)

	skill := hl.Dependencies[1]
	assert.Equal(t, "skills[0]", skill.Field)
	require.Len(t, skill.TransitiveDeps, 1)
	assert.Equal(t, "https://example.com/skills/common/SKILL.md", skill.TransitiveDeps[0].URL)
}

func TestSave_DefaultsVersion(t *testing.T) {
	lf := &LockFile{
		GeneratedAt: testTime,
		Harnesses:   map[string]HarnessLock{},
	}

	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, Save(path, lf))

	loaded, err := Load(path)
	require.NoError(t, err)
	assert.Equal(t, 1, loaded.Version)
}

func TestSave_Header(t *testing.T) {
	lf := &LockFile{
		Version:     1,
		GeneratedAt: testTime,
		Harnesses:   map[string]HarnessLock{},
	}

	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, Save(path, lf))

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(data), "# Generated by fullsend lock — DO NOT EDIT")
}

func TestSave_AtomicWrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "lock.yaml")

	lf1 := &LockFile{
		Version:     1,
		GeneratedAt: testTime,
		Harnesses: map[string]HarnessLock{
			"first": {Source: "harness/first.yaml", SHA256: "aaa", ResolvedAt: testTime},
		},
	}
	require.NoError(t, Save(path, lf1))

	lf2 := &LockFile{
		Version:     1,
		GeneratedAt: testTime,
		Harnesses: map[string]HarnessLock{
			"second": {Source: "harness/second.yaml", SHA256: "bbb", ResolvedAt: testTime},
		},
	}
	require.NoError(t, Save(path, lf2))

	loaded, err := Load(path)
	require.NoError(t, err)
	assert.Nil(t, loaded.Lookup("first"))
	assert.NotNil(t, loaded.Lookup("second"))
}

func TestSave_CreatesDirectories(t *testing.T) {
	path := filepath.Join(t.TempDir(), "deep", "nested", "lock.yaml")

	lf := &LockFile{
		Version:     1,
		GeneratedAt: testTime,
		Harnesses:   map[string]HarnessLock{},
	}
	require.NoError(t, Save(path, lf))

	_, err := os.Stat(path)
	require.NoError(t, err)
}

func TestLookup_NotFound(t *testing.T) {
	lf := &LockFile{
		Version:   1,
		Harnesses: map[string]HarnessLock{},
	}
	assert.Nil(t, lf.Lookup("nonexistent"))
}

func TestLookup_NilLockFile(t *testing.T) {
	var lf *LockFile
	assert.Nil(t, lf.Lookup("anything"))
}

func TestIsStale_MatchingHash(t *testing.T) {
	hl := &HarnessLock{SHA256: "abc123"}
	assert.False(t, hl.IsStale("abc123"))
}

func TestIsStale_DifferentHash(t *testing.T) {
	hl := &HarnessLock{SHA256: "abc123"}
	assert.True(t, hl.IsStale("def456"))
}

func TestLookupDep_DirectMatch(t *testing.T) {
	hl := &HarnessLock{
		Dependencies: []DependencyEntry{
			{URL: "https://example.com/agents/code.md", SHA256: "aaa"},
			{URL: "https://example.com/skills/rust.md", SHA256: "bbb"},
		},
	}

	dep := hl.LookupDep("https://example.com/skills/rust.md")
	require.NotNil(t, dep)
	assert.Equal(t, "bbb", dep.SHA256)
}

func TestLookupDep_TransitiveMatch(t *testing.T) {
	hl := &HarnessLock{
		Dependencies: []DependencyEntry{
			{
				URL:    "https://example.com/skills/rust.md",
				SHA256: "aaa",
				TransitiveDeps: []DependencyEntry{
					{
						URL:    "https://example.com/skills/common.md",
						SHA256: "bbb",
						TransitiveDeps: []DependencyEntry{
							{URL: "https://example.com/policies/sandbox.yaml", SHA256: "ccc"},
						},
					},
				},
			},
		},
	}

	dep := hl.LookupDep("https://example.com/policies/sandbox.yaml")
	require.NotNil(t, dep)
	assert.Equal(t, "ccc", dep.SHA256)
}

func TestLookupDep_NotFound(t *testing.T) {
	hl := &HarnessLock{
		Dependencies: []DependencyEntry{
			{URL: "https://example.com/agents/code.md", SHA256: "aaa"},
		},
	}

	assert.Nil(t, hl.LookupDep("https://example.com/nonexistent"))
}

func TestSetHarness(t *testing.T) {
	lf := &LockFile{Version: 1, GeneratedAt: testTime}

	lf.SetHarness("code", HarnessLock{
		Source: "harness/code.yaml",
		SHA256: "abc",
	})

	hl := lf.Lookup("code")
	require.NotNil(t, hl)
	assert.Equal(t, "abc", hl.SHA256)
}

func TestSetHarness_Replaces(t *testing.T) {
	lf := &LockFile{
		Version:     1,
		GeneratedAt: testTime,
		Harnesses: map[string]HarnessLock{
			"code": {Source: "harness/code.yaml", SHA256: "old"},
		},
	}

	lf.SetHarness("code", HarnessLock{
		Source: "harness/code.yaml",
		SHA256: "new",
	})

	hl := lf.Lookup("code")
	require.NotNil(t, hl)
	assert.Equal(t, "new", hl.SHA256)
}

func TestHarnessNames(t *testing.T) {
	lf := &LockFile{
		Version: 1,
		Harnesses: map[string]HarnessLock{
			"zebra": {},
			"alpha": {},
			"mid":   {},
		},
	}

	names := lf.HarnessNames()
	assert.Equal(t, []string{"alpha", "mid", "zebra"}, names)
}

func TestHarnessNames_Empty(t *testing.T) {
	lf := &LockFile{Version: 1}
	assert.Nil(t, lf.HarnessNames())
}

func TestHarnessNames_NilLockFile(t *testing.T) {
	var lf *LockFile
	assert.Nil(t, lf.HarnessNames())
}

func TestLoad_TransitiveDeps(t *testing.T) {
	content := `version: 1
generated_at: 2026-06-08T12:00:00Z
harnesses:
  code:
    source: harness/code.yaml
    sha256: abc
    resolved_at: 2026-06-08T12:00:00Z
    dependencies:
      - field: skills[0]
        url: https://example.com/skills/rust/SKILL.md
        sha256: def
        fetched_at: 2026-06-08T12:00:00Z
        transitive_deps:
          - field: skills[dep0]
            url: https://example.com/skills/common/SKILL.md
            sha256: ghi
            fetched_at: 2026-06-08T12:00:00Z
`
	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	lf, err := Load(path)
	require.NoError(t, err)

	hl := lf.Lookup("code")
	require.NotNil(t, hl)
	require.Len(t, hl.Dependencies, 1)
	require.Len(t, hl.Dependencies[0].TransitiveDeps, 1)
	assert.Equal(t, "https://example.com/skills/common/SKILL.md", hl.Dependencies[0].TransitiveDeps[0].URL)
}

func TestLoad_MultipleHarnesses(t *testing.T) {
	content := `version: 1
generated_at: 2026-06-08T12:00:00Z
harnesses:
  code:
    source: harness/code.yaml
    sha256: aaa
    resolved_at: 2026-06-08T12:00:00Z
    dependencies: []
  review:
    source: harness/review.yaml
    sha256: bbb
    resolved_at: 2026-06-08T12:00:00Z
    dependencies: []
`
	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	lf, err := Load(path)
	require.NoError(t, err)
	assert.NotNil(t, lf.Lookup("code"))
	assert.NotNil(t, lf.Lookup("review"))
	assert.Nil(t, lf.Lookup("triage"))
}

func TestSetHarness_NilLockFile(t *testing.T) {
	var lf *LockFile
	lf.SetHarness("code", HarnessLock{SHA256: "abc"}) // should not panic
}

func TestIsStale_NilHarnessLock(t *testing.T) {
	var hl *HarnessLock
	assert.True(t, hl.IsStale("anything"))
}

func TestLookupDep_NilHarnessLock(t *testing.T) {
	var hl *HarnessLock
	assert.Nil(t, hl.LookupDep("https://example.com/anything"))
}

func TestLookupDep_MaxDepth(t *testing.T) {
	target := "https://example.com/deep-target"
	leaf := DependencyEntry{URL: target, SHA256: "leaf"}
	for i := 0; i < maxLookupDepth+5; i++ {
		leaf = DependencyEntry{
			URL:            fmt.Sprintf("https://example.com/level-%d", i),
			SHA256:         fmt.Sprintf("hash-%d", i),
			TransitiveDeps: []DependencyEntry{leaf},
		}
	}

	hl := &HarnessLock{Dependencies: []DependencyEntry{leaf}}
	assert.Nil(t, hl.LookupDep(target), "should return nil for deps beyond maxLookupDepth")
}

func TestLoad_EmptyHarnesses(t *testing.T) {
	content := `version: 1
generated_at: 2026-06-08T12:00:00Z
harnesses: {}
`
	path := filepath.Join(t.TempDir(), "lock.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	lf, err := Load(path)
	require.NoError(t, err)
	require.NotNil(t, lf)
	assert.Empty(t, lf.Harnesses)
}

func TestSave_VersionFollowsWorkflowDependency(t *testing.T) {
	skillDep := DependencyEntry{Field: "skills[0]", URL: "https://example.com/skills/a", SHA256: "aaa", Type: "directory"}
	workflowDep := DependencyEntry{Field: WorkflowField, URL: "https://example.com/defs/sample", SHA256: "bbb", Type: "directory"}
	tests := []struct {
		name string
		deps []DependencyEntry
		want int
	}{
		{"no workflow dependency", []DependencyEntry{skillDep}, 1},
		{"workflow dependency", []DependencyEntry{skillDep, workflowDep}, 2},
		{"workflow dependency nested", []DependencyEntry{{Field: "skills[1]", URL: "https://example.com/skills/b", TransitiveDeps: []DependencyEntry{workflowDep}}}, 2},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// A stale version on the struct is overwritten from the content.
			lf := &LockFile{Version: 2, GeneratedAt: testTime}
			lf.SetHarness("triage", HarnessLock{Source: "harness/triage.yaml", Dependencies: tt.deps})
			path := filepath.Join(t.TempDir(), "lock.yaml")
			require.NoError(t, Save(path, lf))
			assert.Equal(t, tt.want, lf.Version)

			data, err := os.ReadFile(path)
			require.NoError(t, err)
			assert.Contains(t, string(data), fmt.Sprintf("\nversion: %d\n", tt.want))
			loaded, err := Load(path)
			require.NoError(t, err)
			assert.Equal(t, tt.want, loaded.Version)
		})
	}

	t.Run("dropping the workflow harness writes version 1 again", func(t *testing.T) {
		lf := &LockFile{GeneratedAt: testTime}
		lf.SetHarness("triage", HarnessLock{Dependencies: []DependencyEntry{skillDep}})
		lf.SetHarness("pipeline", HarnessLock{Dependencies: []DependencyEntry{workflowDep}})
		path := filepath.Join(t.TempDir(), "lock.yaml")
		require.NoError(t, Save(path, lf))
		loaded, err := Load(path)
		require.NoError(t, err)
		assert.Equal(t, 2, loaded.Version)

		delete(loaded.Harnesses, "pipeline")
		require.NoError(t, Save(path, loaded))
		reloaded, err := Load(path)
		require.NoError(t, err)
		assert.Equal(t, 1, reloaded.Version)
	})
}

func TestLoad_AcceptedVersions(t *testing.T) {
	for _, tt := range []struct {
		version int
		wantErr bool
	}{{1, false}, {2, false}, {3, true}, {0, true}} {
		t.Run(fmt.Sprintf("version %d", tt.version), func(t *testing.T) {
			content := fmt.Sprintf("version: %d\ngenerated_at: 2026-06-08T12:00:00Z\nharnesses: {}\n", tt.version)
			path := filepath.Join(t.TempDir(), "lock.yaml")
			require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
			lf, err := Load(path)
			if tt.wantErr {
				require.Error(t, err)
				assert.Contains(t, err.Error(), fmt.Sprintf("unsupported lock file version %d (expected 1 or 2)", tt.version))
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tt.version, lf.Version)
		})
	}
}
